# NumPy
- Short for **Num**erical **Py**thon
- Numpy is the core library for **scientific computing in Python and used for numerical computations**.

### why do we need numpy arrays ?
- NumPy arrays are significantly **faster for numerical operations** compared to Python lists
- NumPy provides a rich set of mathematical functions and operations optimized for arrays, including linear algebra operations, Fourier transforms, random number generation, etc. which are not readily available or as efficient with standard Python lists.
- NumPy's core feature is the **ndarray, a powerful N-dimensional array object that allows for efficient manipulation of large datasets**. These are **multidimensional array object**


### Topics covered:
- creating arrays from list or tuple
- np methods to create arrays: zeros, ones, full, eye, random, randomint, arrange, etc


## Few terms and definitions
- A numpy array is a grid of values, all of the same type, and is indexed by a tuple of nonnegative integers. 
- **The number of dimensions is the rank of the array**
-  The **shape** of an array is a tuple of integers giving the size of the array along each dimension.
- A rank 1 array (also known as a 1-dimensional array) is essentially a list of values.


**We can initialize numpy arrays from nested Python iterables like lists, tuples, etc.**

**We access elements using square brackets:[]**

In [ ]:
# !pip install numpy

In [2]:
import numpy as np

In [8]:
# lets create an array of shape (6): i.e. 1D array with 6 elements

l = [50, 30, 72, 65, 59, 22] # scores in 6 subjects
a = np.array(l)   # Create a rank 1(i.e. 1D) array

print(a)
print(type(a))  #  <class 'numpy.ndarray'>
print(a.ndim)   # lets look at dim
print(a.shape)  # Lets look at shape, i.e. the number of elements (6,)

[50 30 72 65 59 22]
<class 'numpy.ndarray'>
1
(6,)


In [9]:
# I can create numpy array from  tuples too
t = (50, 30, 72, 65, 59, 22)
a = np.array(t)   # Create a rank 1(i.e. 1D) array

print(a)
print(type(a))  # <class 'numpy.ndarray'>
print(a.ndim)   # lets look at dim
print(a.shape)  # Lets look at shape, i.e. the number of elements (6,)

[50 30 72 65 59 22]
<class 'numpy.ndarray'>
1
(6,)


In [4]:
# Now lets create an array of dimension 2D each with 2 and 3 elements 
# Each row represents a student, each column represents a subject (Math, Science, English)
l = [
    [85, 90, 78],  # Student 1
    [68, 76, 92]   # Student 2
]
scores = np.array(l)

print(scores)
print(scores.ndim)    # 2
print(scores.shape)   # (2, 3)

[[85 90 78]
 [68 76 92]]
<class 'numpy.ndarray'>
2
(2, 3)


In [5]:
# Creating a 3D array with shape (2, 3, 5)
b = np.array([
    [  # First block (depth index 0)
        [1, 2, 3, 4, 5],      # row=0
        [6, 7, 8, 9, 10],     # row=1
        [11, 12, 13, 14, 15]  # row=2
    ],
    
    [  # Second block (depth index 1)
        [16, 17, 18, 19, 20], # row=0
        [21, 22, 23, 24, 25], # row=1
        [26, 27, 28, 29, 30]  # row=2
    ]
])

print(b)
print(b.ndim)    # 3
print(b.shape)   # (2, 3, 5)

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]]

 [[16 17 18 19 20]
  [21 22 23 24 25]
  [26 27 28 29 30]]]
3
(2, 3, 5)
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
<class 'numpy.ndarray'> 3
(2, 2, 2)


In [7]:
# lets create 3D array of shape (2,3,2)
b = np.array([
    [ # First block (depth index 0)
        [1, 2],
        [5, 8],
        [3, 4]
    ],
    [ # Second block (depth index 1)
        [5, 6],
        [3, 0],
        [7, 8]
    ]
])
print(b)
print(b.ndim)    #  3
print(b.shape)   # (2, 3, 2)
##################################################

[[[1 2]
  [5 8]
  [3 4]]

 [[5 6]
  [3 0]
  [7 8]]]
3
(2, 3, 2)


**Numpy also provides many methods to create special arrays**

In [24]:
# creating matrices of all zeros
# create a 1D array of 10 elements with all 0
a = np.zeros((10)) 
print(a)
print(a.ndim)
print(a.shape)
print("#####################")

# Create an 3X3 array of all zeros
a = np.zeros((3,3))   
print(a)              
print("#####################")

# Create an 3X5 array of all zeros
a = np.zeros((3,5))
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
1
(10,)
#####################
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
#####################
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [13]:
# creating matrices of all 1 or some constant
# create arrays of all 1
b = np.ones((4))    
print(b)           
print("######################")

# create 3x5 array of all 1
a = np.ones((3,5)) 
print(a)
print("###############################")

# fill an array with some constant value 5
a = np.full((3), fill_value=5)
print(a)

# fill an 3X4 array with some constant value 9
a = np.full((3,4), fill_value=9)
print(a)

[1. 1. 1. 1.]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[5 5 5]
[[9 9 9 9]
 [9 9 9 9]
 [9 9 9 9]]
[[7 7]
 [7 7]]


In [25]:
# creating identity matrices

# Lets create an array of identity matrix
d = np.eye(3)         
print(d)              
print("######################")

#  Lets create an 3X5 array of identity matrix
d = np.eye(3, 5)
print(d)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
######################
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


In [36]:
# create array wth random numbers

# Create an 1Darray of size 10 filled with random values between 0 and 1
e = np.random.random((10))  
print(e)
###########################

# Create an 2X4 array filled with random values between 0 and 1
e = np.random.random( (2,4) )  
print(e)
###########################

# Generate a 1D array with 8 elements with random integers between -10 (inclusive) and 15 (exclusive)
e = np.random.randint(-10, 15, size=(8,))
print(e)
###########################
# Generate a 2X4X8 matrix with random integers between -10 (inclusive) and 15 (exclusive)
e = np.random.randint(-10, 15, size=(2, 4, 8))
print(e)

[9.06828442e-01 2.72132249e-01 6.47690121e-01 5.20376995e-04
 3.52568856e-01 3.04781258e-01 1.64655853e-01 5.34089419e-01
 4.84829971e-01 6.92436033e-01]
[[0.26941233 0.24412552 0.16829104 0.21876422]
 [0.558102   0.40383617 0.06489225 0.25391541]]
[ 1 -4 -9 -8  6 -6  6 13]
[[  6   6  -9  -9  11  12  -6 -10]
 [-10   8  -9  10   1  -5  12  -7]
 [ 12   0  13   6  -5  13  -6   9]
 [ -9  -5  11   0   5   5 -10  -2]]


In [32]:
# creating arrays using method arange(start_idx=0, stop_idx, step=1)

# Example 1: # Creates an array from 0 to 4
arr = np.arange(5)  
print(arr)

# Example 2: Creates an array from 2 to 9
arr = np.arange(2, 10)  
print(arr)

# Example 3: Creates an array from 1 to 9 with a step of 2
arr = np.arange(1, 10, 2)  
print(arr)

# Example 4: Creates an array of floats from 0 to 0.9 with step=0.1
arr = np.arange(0, 1, 0.1)  
print(arr)

[0 1 2 3 4]
[2 3 4 5 6 7 8 9]
[1 3 5 7 9]
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


# STOP

### resources

- Good tutorial on numpy: https://www.machinelearningplus.com/python/numpy-tutorial-part1-array-python-examples/ and https://www.machinelearningplus.com/python/numpy-tutorial-python-part2/
