## Transpose

In [13]:
import numpy as np

In [14]:
# Transpose
# Application:Preparing data for algorithms 
# like matrix multiplication or PCA (Principal Component Analysis), which
# require certain shape conventions.

# If shape of x is 2X3. Then shape of x.T is 3X2
x = np.array([
    [1, 2, 3], 
    [4, 5 ,6]] 
)
print(x)

print(x.T)  
print("####################")

# If shape of x is 3X2. Then shape of x.T is 2X3
x = np.array([[1,2],
              [3,4],
              [5,6]]
)
print(x)
print(x.T)  
print("####################")

# Note that taking the transpose of a rank 1 array does nothing:
v = np.array([1,2,3])
print(v)    
print(v.T)  

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]
####################
[[1 2]
 [3 4]
 [5 6]]
[[1 3 5]
 [2 4 6]]
####################
[1 2 3]
[1 2 3]


### flatten
**flatten**: Convert a multi-dimensional array into a **one-dimensional array**. This is particularly useful when you want to simplify the structure of your data for processing or analysis. 
- Many ML models (e.g., logistic regression, decision trees) expect 1D feature vectors, not 2D matrices.
- Many CNN model requires 1D data 
- Suppose Temperature Sensor Grid (e.g., Smart Building or IoT Device) is mounted on a building and uses a 3×3 array of temperature sensors placed in a room (ceiling tiles or wall grid). Each number represents temperature (°C or °F) at a specific grid point. We flatten the data and then calculate mean,std_dev, etc
- Touchscreen or Tactile Grid Sensor (e.g., Wearable Tech or Robotics): A grid of touch-sensitive elements or capacitive sensors. The readings might show the force or presence of a finger or object.

**In all above cases, the data is  spatially distributed**


In [15]:
# lets flatten an array using method flatten():
# NOTE: This returns copy

# Create a 2D NumPy array (matrix)
array_2d = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]])

print("Original 2D Array:\n",array_2d)

# Flatten the 2D array into a 1D array
flattened_array = array_2d.flatten()

print("\nFlattened Array:\n", flattened_array)

Original 2D Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Flattened Array:
 [1 2 3 4 5 6 7 8 9]


### ravel
Function that returns a flattened view of a multi-dimensional array, i.e. it creates a 1D array that shares the same underlying data buffer as the original array, if possible. **Modifying the raveled array can therefore affect the original array**

In [16]:
# ravel: Modifying the raveled array can affect the original array

arr = np.array([[1, 2, 3],
                [4, 5, 6]])

raveled_arr = arr.ravel()
print(raveled_arr)

# Modifying raveled_arr effects arr
raveled_arr[0] = 99
print(arr)

[1 2 3 4 5 6]
[[99  2  3]
 [ 4  5  6]]


## reshape

**reshape()**: The opposite of the flatten() operation in NumPy is **reshape()**, which reshapes the array to a new shape of the array, as long as the total number of elements remains the same.

## Can We Reshape Into any Shape?
Yes, as long as the elements required for reshaping are equal in both shapes.

###### Why reshape?
- Most machine learning libraries (like scikit-learn) expect 2D input: shape (n_samples, n_features).
```
arr = np.array([5, 10, 15, 20])  # Shape = (4,)

# Reshape into (4, 1): 4 samples, 1 feature
reshaped = arr.reshape(-1, 1)
```
  
- Convert flat image to 2D or 3D format
- You need a 2D structure to do matrix multiplication, transpose, or broadcasting.
```
a = np.array([1, 2, 3])         # Shape = (3,)
b = np.array([4, 5, 6])         # Shape = (3,)

# Convert to row and column vectors
a_row = a.reshape(1, 3)         # Shape = (1, 3)
b_col = b.reshape(3, 1)         # Shape = (3, 1)

result = np.dot(a_row, b_col)  # Shape = (1,1) → scalar result
```

In [17]:
# Reshape: lets reshape a flattened array

# Create a flattened array of size 18
flattened_array = np.arange(18)  # This creates an array with values from 0 to 17
print("Flattened Array:",flattened_array)


# Reshape into different sizes

# 1. Reshape to 2D array of shape (2, 9)
reshaped_2d_2x9 = flattened_array.reshape(2, 9)
print("\nReshaped Array (2x9):\n",reshaped_2d_2x9)
print(type(reshaped_2d_2x9), reshaped_2d_2x9.ndim)
print(reshaped_2d_2x9.shape) # (2, 9)          


Flattened Array: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]

Reshaped Array (2x9):
[[ 0  1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16 17]]
<class 'numpy.ndarray'> 2
(2, 9)


In [18]:
flattened_array = np.arange(18)  # This creates an array with values from 0 to 17
print("Flattened Array:",flattened_array)

# 2. Reshape to 2D array of shape (3, 6)
reshaped_2d_3x6 = flattened_array.reshape(3, 6)
print("\nReshaped Array (3x6):\n",reshaped_2d_3x6)


Flattened Array: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]

Reshaped Array (3x6):
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]


In [19]:
flattened_array = np.arange(18)  # This creates an array with values from 0 to 17
print("Flattened Array:",flattened_array)

# 3. Reshape to 2D array of shape (6, 3)
reshaped_2d_6x3 = flattened_array.reshape(6, 3)
print("\nReshaped Array (6x3):",reshaped_2d_6x3)


Flattened Array: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]

Reshaped Array (6x3):
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]


In [20]:
flattened_array = np.arange(18)  # This creates an array with values from 0 to 17
print("Flattened Array:",flattened_array)

# 4. Reshape to 3D array of shape (2, 3, 3)
reshaped_3d_2x3x3 = flattened_array.reshape(2, 3, 3)
print("\nReshaped Array (2x3x3):\n",reshaped_3d_2x3x3)

Flattened Array: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]

Reshaped Array (2x3x3):
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]]


In [21]:

flattened_array = np.arange(18)  # This creates an array with values from 0 to 17
print("Flattened Array:",flattened_array)

# 5. Reshape to 3D array of shape (3, 2, 3)
reshaped_3d_3x2x3 = flattened_array.reshape(3, 2, 3)
print("\nReshaped Array (3x2x3):")
print(reshaped_3d_3x2x3)


Flattened Array: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]

Reshaped Array (3x2x3):
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]]]


In [22]:
# Another way to flatten is to use reshape with argument -1:
# -1 would mean that numpy would figure out the shape

# 3D array to 1D array:

array = np.array([[1, 2, 3, 4, 5],
                  [4, 5, 6, 7, 8],
                  [7, 8, 9, 3, 4]])
print(array)

# convert it into 1D
reshaped = array.reshape((-1))
print(reshaped)
#####################

# convert it into 2D of shape 5X3
reshaped = array.reshape((-1, 3))
print(reshaped)
#######################

# convert it into 2D of shape 5X3
reshaped = array.reshape((5, -1))
print(reshaped)
######################

[[1 2 3 4 5]
 [4 5 6 7 8]
 [7 8 9 3 4]]
[1 2 3 4 5 4 5 6 7 8 7 8 9 3 4]
[[1 2 3]
 [4 5 4]
 [5 6 7]
 [8 7 8]
 [9 3 4]]
[[1 2 3]
 [4 5 4]
 [5 6 7]
 [8 7 8]
 [9 3 4]]


### vstack

In [23]:
x1 = np.array([10, 20, 30, 40, 50])  
x2 = np.array([20, 40, 60, 80, 100])
x3 = np.array([18, 40, 50, 20,  30]) 
x4 = np.array([90, 82, 55, 40, 20]) 

X = np.vstack((x1, x2, x3, x4))
print(X)

[[ 10  20  30  40  50]
 [ 20  40  60  80 100]
 [ 18  40  50  20  30]
 [ 90  82  55  40  20]]
