## Linear Algebra

### Topics covered:
- np.linalg methods: solve linear equations
- np.linalg methods: eigen values, eigen vectors
- (OPTIONAL) np.linalg methods: Singular Value Decomposition (SVD), Matrix Rank

### Solving Linear Systems
e.g.1: 
```
Solve
1*x1  + 2*x2 = 5
3*x1  + 4*x2 = 11  

=>
Solve Ax = b where:
A = [[1, 2], 
     [3, 4]]
b = [5, 11]
x = [x1, x2]

So, x = A_inverse * b
```


In [21]:
from numpy.linalg import solve

A = np.array([[1, 2], 
              [3, 4]])
b = np.array([5, 11])

x = solve(A, b)
print("\nSolution to Ax = b is x=",x)
print("\nVerification (Ax should equal b):", A @ x) # Should match b


Solution to Ax = b is x= [1. 2.]

Verification (Ax should equal b): [ 5. 11.]


## np.linalg: eigen values and eigen vectors
Uses:
- To reduce the dimensionality of large datasets while preserving the most important variance (information).
- To rank web pages based on their importance.
- To analyze the long-term behavior of dynamic systems (e.g., population growth, vibrations, or circuits).

In [22]:
from numpy.linalg import eig

# How to calculate eigen values/ eigen vestors and also verify for 2X2 matrix
# TAKEN from Lang

# Define a 2x2 matrix
A = np.array([[1, 4], 
              [2, 3]])

eigenvalues, eigenvectors = eig(A)

print(f"Matrix A:\n{A}")
print(f"\nEigenvalues:{eigenvalues}")
print(f"\nEigenvectors (columns):\n{eigenvectors}\n\n")

print(f"Eigen value: {eigenvalues[0]} and its corresponding eigen vector: {eigenvectors[:, 0]}")
print(f"Eigen value: {eigenvalues[1]} and its corresponding eigen vector: {eigenvectors[:, 1]}")

##################################

# First eigenvalue and eigenvector
lambda1 = eigenvalues[0]
v1 = eigenvectors[:, 0]

Av1 = A @ v1
lambda1_v1 = lambda1 * v1

print("\nVerifying First Eigenpair:")
print("A @ v1 =", Av1)
print("λ1 * v1 =", lambda1_v1)
print("Match? ->", np.allclose(Av1, lambda1_v1)) # Returns True if two arrays are element-wise equal within a tolerance.
####################################

# Second eigenvalue and eigenvector
lambda2 = eigenvalues[1]
v2 = eigenvectors[:, 1]

Av2 = A @ v2
lambda2_v2 = lambda2 * v2

print("\nVerifying Second Eigenpair:")
print("A @ v2 =", Av2)
print("λ2 * v2 =", lambda2_v2)
print("Match? ->", np.allclose(Av2, lambda2_v2))


Matrix A:
[[1 4]
 [2 3]]

Eigenvalues:[-1.  5.]

Eigenvectors (columns):
[[-0.89442719 -0.70710678]
 [ 0.4472136  -0.70710678]]


Eigen value: -1.0 and its corresponding eigen vector: [-0.89442719  0.4472136 ]
Eigen value: 5.0 and its corresponding eigen vector: [-0.70710678 -0.70710678]

Verifying First Eigenpair:
A @ v1 = [ 0.89442719 -0.4472136 ]
λ1 * v1 = [ 0.89442719 -0.4472136 ]
Match? -> True

Verifying Second Eigenpair:
A @ v2 = [-3.53553391 -3.53553391]
λ2 * v2 = [-3.53553391 -3.53553391]
Match? -> True


In [23]:
# How to calculate eigen values/ eigen vectors and also verify for 3X3 matrix
# Taken from Lang
from numpy.linalg import eig

# # Set print precision
# np.set_printoptions(precision=3, suppress=True)

# Define a 3x3 matrix
A = np.array([[2, 1, 0],
              [0, 1, -1],
              [0, 2, 4]])

eigenvalues, eigenvectors = eig(A)

print(f"Matrix A:\n{A}")
print(f"\nEigenvalues:\n{np.round(eigenvalues, 3)}")
print(f"\nEigenvectors (columns):\n{np.round(eigenvectors, 3)}\n\n")

print(f"Eigen value: {eigenvalues[0]} and its corresponding eigen vector: {eigenvectors[:, 0]}")
print(f"Eigen value: {eigenvalues[1]} and its corresponding eigen vector: {eigenvectors[:, 1]}")
print(f"Eigen value: {eigenvalues[2]} and its corresponding eigen vector: {eigenvectors[:, 2]}")

##################################

# First eigenpair
lambda1 = eigenvalues[0]
v1 = eigenvectors[:, 0]

Av1 = A @ v1
lambda1_v1 = lambda1 * v1

print("\nVerifying First Eigenpair:")
print("A @ v1 =", np.round(Av1, 3))
print("λ1 * v1 =", np.round(lambda1_v1, 3))
print("Match? ->", np.allclose(Av1, lambda1_v1))

##################################

# Second eigenpair
lambda2 = eigenvalues[1]
v2 = eigenvectors[:, 1]

Av2 = A @ v2
lambda2_v2 = lambda2 * v2

print("\nVerifying Second Eigenpair:")
print("A @ v2 =", np.round(Av2, 3))
print("λ2 * v2 =", np.round(lambda2_v2, 3))
print("Match? ->", np.allclose(Av2, lambda2_v2))

##################################

# Third eigenpair
lambda3 = eigenvalues[2]
v3 = eigenvectors[:, 2]

Av3 = A @ v3
lambda3_v3 = lambda3 * v3

print("\nVerifying Third Eigenpair:")
print("A @ v3 =", np.round(Av3, 3))
print("λ3 * v3 =", np.round(lambda3_v3, 3))
print("Match? ->", np.allclose(Av3, lambda3_v3))


Matrix A:
[[ 2  1  0]
 [ 0  1 -1]
 [ 0  2  4]]

Eigenvalues:
[2. 2. 3.]

Eigenvectors (columns):
[[ 1.     1.     0.408]
 [ 0.    -0.     0.408]
 [ 0.     0.    -0.816]]


Eigen value: 2.0 and its corresponding eigen vector: [1. 0. 0.]
Eigen value: 2.0 and its corresponding eigen vector: [ 1.0000000e+00 -4.4408921e-16  4.4408921e-16]
Eigen value: 3.0 and its corresponding eigen vector: [ 0.40824829  0.40824829 -0.81649658]

Verifying First Eigenpair:
A @ v1 = [2. 0. 0.]
λ1 * v1 = [2. 0. 0.]
Match? -> True

Verifying Second Eigenpair:
A @ v2 = [ 2. -0.  0.]
λ2 * v2 = [ 2. -0.  0.]
Match? -> True

Verifying Third Eigenpair:
A @ v3 = [ 1.225  1.225 -2.449]
λ3 * v3 = [ 1.225  1.225 -2.449]
Match? -> True


## (OPTIONAL) SVD, Rank
Singular Value Decomposition (SVD) is a powerful matrix factorization technique that breaks down any real or complex matrix A into three constituent matrices:

A = U * S * Vt

Where:

U is an orthogonal matrix (left singular vectors)

S (Sigma) is a diagonal matrix of singular-values (non-negative, usually ordered from largest to smallest)

Vt is the transpose of an orthogonal matrix (right singular vectors)

In [24]:
from numpy.linalg import svd

A = np.array([[1, 2],
              [3, 4],
              [5, 6]])

U, Sing_val, Vt = svd(A)
print("\nU matrix:")
print(U)

print("\nSingular values:")
print(Sing_val)
# Create Sigma diagonal matrix from singular values
Sigma = np.zeros(A.shape)
Sigma[:len(Sing_val), :len(Sing_val)] = np.diag(Sing_val)
print("\nSigma matrix from singular values:")
print(Sigma)

print("\nV transpose matrix:")
print(Vt)


# Reconstruct A
A_reconstructed = U @ Sigma @ Vt
print("\nReconstructed matrix:")
print(A_reconstructed)

print("###################################")
from numpy.linalg import matrix_rank

E = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

rank = matrix_rank(E)
print("\nMatrix rank:")
print(rank)  # Will be 2 (linearly dependent rows)


U matrix:
[[-0.2298477   0.88346102  0.40824829]
 [-0.52474482  0.24078249 -0.81649658]
 [-0.81964194 -0.40189603  0.40824829]]

Singular values:
[9.52551809 0.51430058]

Sigma matrix from singular values:
[[9.52551809 0.        ]
 [0.         0.51430058]
 [0.         0.        ]]

V transpose matrix:
[[-0.61962948 -0.78489445]
 [-0.78489445  0.61962948]]

Reconstructed matrix:
[[1. 2.]
 [3. 4.]
 [5. 6.]]
###################################

Matrix rank:
2
