## Linear Algebra

### Topics covered:
- np.linalg methods: determinant, inverse of square matrix

##  np.linalg: determinant, inverse, 
- np.linalg provides methods to find determiant and inverse of a **square matrix**

#### Application  of determinant
- To know if a matrix is invertible (non-zero determinant -> invertible)
- Solve A*x=b : If **det(A) != 0**, the system has a unique solution. If **det(A) = 0**, the system is singular (either no solution or infinitely many)
- When you apply a linear transformation (e.g., stretching, rotating, shearing) to a 2D geometric shape using a matrix (T), the absolute value of the determinant of that matrix tells you how much the shape's area or volume is scaled.

 **New Area = ∣det(T)∣ × Original Area**

In [1]:
import numpy as np
from numpy.linalg import det
from numpy.linalg import inv

In [2]:
# Determinant of 2x2 matrix

A = np.array([[2, 1], 
              [3, 5]]
)

det_A = det(A)
print("Determinant of 2x2 matrix A:", round(det_A, 3))

Determinant of 2x2 matrix A: 7.0


In [3]:
# Determinant of 3x3 matrix
A = np.array([[2, 1, 0],
              [0, 1, -1],
              [0, 2, 4]]
)

det_A = det(A)
print("Determinant of 3x3 matrix A:", round(det_A, 3))

Determinant of 3x3 matrix A: 12.0


In [4]:
# Inverse of a 2X2 matrix
A = np.array([[1, 2], 
              [3, 4]])
A_inv = inv(A)
print("Inverse of Matrix:\n", A_inv)

# Verification: A @ A_inv should be an identity matrix
print("\nVerification (A × A_inv should be I):\n", np.round(A @ A_inv)) 

Inverse of Matrix:
 [[-2.   1. ]
 [ 1.5 -0.5]]

Verification (A × A_inv should be I):
 [[1. 0.]
 [0. 1.]]


In [5]:
# Inverse of a 3X3 matrix

A = np.array([[2, 1, 0],
              [0, 1, -1],
              [0, 2, 4]])
A_inv = inv(A)
print("Inverse of Matrix:\n", A_inv)

# Verification: A @ A_inv should be an identity matrix
print("\nVerification (A × A_inv should be I):\n",np.round(A @ A_inv)) 

Inverse of Matrix:
 [[ 0.5        -0.33333333 -0.08333333]
 [ 0.          0.66666667  0.16666667]
 [-0.         -0.33333333  0.16666667]]

Verification (A × A_inv should be I):
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [7]:
# Application of inverse to solve 2 variable linear equation:

# 1*x1  + 2*x2 = 5
# 3*x1  + 4*x2 = 11  
# Here we can rewrite above as A*x = b, where
# A = [[1, 2], 
#      [3, 4]]
# b = [5, 11]
# So, x = A_inv * b
# lets find x:
A = np.array([[1, 2], 
              [3, 4]]
)
A_inv = inv(A)
b = np.array([5, 11]).T # transpose because b should be 2X1 matrix

x = np.matmul(A_inv,b)
print(x)

[1. 2.]
