### Topics covered:
- filtering

import numpy as np

In [3]:
# On 1D

cont = [4, 7, 2, 3, 9, 3, 6, 2, 1, 7] # water contaminant reading
a = np.array(cont)

# Filter: select elements equal to 3
mask = (a == 3)
# print(mask)
print(a[mask]) 
print(len(a[mask])) # gives count
################################

# Filter: All elements not equal to 3
mask = (a != 3)
print(a[mask]) 
################################

# Filter: All elem > 2 # UNHEALTHY water
mask = (a > 2)
print(a[mask])     
################################

# Filter: All elem > 2 and < 5 # MODERATE
mask = (a > 2) & (a < 5)
print(a[mask]) 
################################

# select elements less than 2 or greater than 4:
mask = (a < 2) | (a > 4)
print(a[mask])
################################

[3 3]
2
[4 7 2 9 6 2 1 7]
[4 7 3 9 3 6 7]
[4 3 3]
[7 9 6 1 7]


In [5]:
# (ADVANCED) On 2D

# Contaminant levels for 4 cities (columns: [Contaminant A, Contaminant B])
water_data = np.array([
    [1, 2],  # City 1
    [3, 4],  # City 2
    [3, 4],  # City 3
    [8, 3],  # City 4
])

# Select only column 1 (Contaminant A)
cont_A = water_data[:, 0]
print(cont_A)

# 1. Filter: find all contaminant A readings equal to 3 (Warning Level)
mask = (cont_A == 3)
print( cont_A[mask])
###################################

# 2. Count how many times warning level 3 appears in Contaminant A
mask = (cont_A == 3)
print(np.sum(mask))
###################################

# 3. Readings in Contaminant A NOT equal to 3
mask = (cont_A != 3)
print(cont_A[mask])
###################################

# 4. Readings in Contaminant A above 2 (considered UNHEALTHY)
mask = (cont_A > 2)
print(cont_A[mask])
###################################

# 5. Moderate concern levels in Contaminant A (>2 and <5)
mask = (cont_A > 2) & (cont_A < 5)
print(cont_A[mask])
###################################

# 6: Apply condition: A > 3 and B > 2
mask = (water_data[:, 0] > 3) & (water_data[:, 1] > 2)
print( water_data[mask])
###################################

# 7. OR condition: Contaminant A > 6 OR Contaminant B < 3
mask = (water_data[:, 0] > 6) | (water_data[:, 1] < 3)
print(water_data[mask])


[3 3]
2
[1 8]
[3 3 8]
[3 3]
[[8 3]]
[[1 2]
 [8 3]]
