### Topics covered:
- np.linalg methods: determinant, inverse, solve linear equations
- np.linalg methods: eigen values, eigen vectors
- (OPTIONAL) np.linalg methods: Singular Value Decomposition (SVD), Matrix Rank

## Linear Algebra
### Matrix multiplication and dot product
- matrix multiplication requires that the **number of columns in the first matrix must match the number of rows in the second matrix**
- If A is **n X m** matrix and B is **m X p** matrix, then matrix multiplication gives **n X p** matrix

e.g1:
```
A = [[1, 2],    B = [[5, 6],
     [3, 4]]         [7, 8]]
 Here A is 2X2 and B is 2X2 matrix.

A @ B = [
  [(1*5 + 2*7), (1*6 + 2*8)],
  [(3*5 + 4*7), (3*6 + 4*8)]
]
= [
  [5+14, 6+16],
  [15+28, 18+32]
]
= [
  [19, 22],
  [43, 50]
]
```

e.g.2
```
A = [[1, 2, 3],
     [4, 5, 6]]
A is 2×3

B = [[7, 8],
     [9, 10],
     [11, 12]]
B is 3×2

A @ B 
= [ (1×7+2×9+3×11)   (1×8+2×10+3×12)
    (4×7+5×9+6×11)   (4×8+5×10+6×12)
  ]
= [ 58   64
    139  154
  ] 

```

e.g.3:
```
A = [[1, 2],
     [3, 4],
     [5, 6]]
 3x2 matrix

B = [[7, 8, 9],
     [10, 11, 12]]
 2x3 matrix

A @ B
= [ 
    (1×7+2×10)   (1×8+2×11)   (1×9+2×12)
    (3×7+4×10)   (3×8+4×11)   (3×9+4×12) 
    (5×7+6×10)   (5×8+6×11)   (5×9+6×12)
 ]

= [[ 27  30  33]
   [ 61  68  75]
   [ 95 106 117]]
```


In [13]:
# A is 2x2 matrix, and B is 2X2 matrix

A = np.array([
    [1, 2],
    [3, 4] 
])

B = np.array([
    [5, 6],
    [7, 8] 
])


# 3 ways to perform Matrix multiplication 
# result = A @ B  
# result = np.matmul(A, B)
result = np.dot(A, B)

print("2x2 Matrix Multiplication:")
print(result)

2x2 Matrix Multiplication:
[[19 22]
 [43 50]]


In [38]:
# A is 2x3 matrix, and B is 3X2 matrix

A = np.array([[1, 2, 3],
              [4, 5, 6]])  # 2x3 matrix

B = np.array([[7, 8],
              [9, 10],
              [11, 12]])    # 3x2 matrix

# 3 ways to perform Matrix multiplication 
result = A @ B 
# result = np.matmul(A, B) 
# result = np.dot(A, B)

print("Result of matrix multiplication:")
print(result)

Result of matrix multiplication:
[[ 58  64]
 [139 154]]


In [39]:
# A is 3x2 matrix, and B is 2X3 matrix

A = np.array([[1, 2],
              [3, 4],
              [5, 6]])  # 3x2 matrix

B = np.array([[7, 8, 9],
              [10, 11, 12]])  # 2x3 matrix

# 3 ways to perform Matrix multiplication 
result = A @ B 
# result = np.matmul(A, B) 
# result = np.dot(A, B)

print("Result of matrix multiplication:")
print(result)

Result of matrix multiplication:
[[ 27  30  33]
 [ 61  68  75]
 [ 95 106 117]]


####  dot product of vectors
- We use the **dot function to compute inner products of 2 vectors, to multiply a vector by a matrix, and to multiply matrices**.
- dot is available both as a function in the numpy module and as an instance method of array objects

In [40]:
# Here we do dot product between two vectors

v = np.array([7,    8,    9]) # Candidate's scores on 3 subjects
w = np.array([0.1, 0.8, 0.1]) #  Weights for each subject

# Inner product of vectors; both produce same result
print(np.dot(v, w)) # Weighted score calculation using dot product
print(v.dot(w))

8.0


##  np.linalg: determinant, inverse, 
- np.linalg provides some very useful methods.

#### Application  of determinant
- To know if a matrix is invertible (non-zero determinant → invertible)
- Solve A⋅x=b : If **det(A) != 0**, the system has a unique solution. If **det(A) = 0**, the system is singular (either no solution or infinitely many)
- When you apply a linear transformation (e.g., stretching, rotating, shearing) to a 2D geometric shape using a matrix (T), the absolute value of the determinant of that matrix tells you how much the shape's area or volume is scaled.

 **New Area = ∣det(T)∣ × Original Area**

 (Example provided in next notebook)

In [19]:
# some useful method of np.linalg library
from numpy.linalg import det

A = np.array([[2, 1], 
              [3, 5]])

det_A = det(A)
print("Determinant of 2x2 matrix A:", round(det_A, 3))

A = np.array([[2, 1, 0],
              [0, 1, -1],
              [0, 2, 4]])
det_A = det(A)
print("Determinant of 3x3 matrix A:", round(det_A, 3))

Determinant of 2x2 matrix A: 7.0
Determinant of 3x3 matrix A: 12.0


In [20]:
# Inverse of a Matrix
from numpy.linalg import inv

# of 2X2 matrix
A = np.array([[1, 2], 
              [3, 4]])
A_inv = inv(A)
print("Inverse of Matrix:\n", A_inv)
print("\nVerification (A × A_inv should be I):\n", np.round(A @ A_inv)) # Should be identity matrix
print("#################################")

# of 3X3 matrix
A = np.array([[2, 1, 0],
              [0, 1, -1],
              [0, 2, 4]])
A_inv = inv(A)
print("Inverse of Matrix:\n", A_inv)
print("\nVerification (A × A_inv should be I):\n",np.round(A @ A_inv)) # Should be identity matrix
print("#################################")

# Application of inverse
# imagine trying to solve: 
# 1*x1  + 2*x2 = 5
# 3*x1  + 4*x2 = 11  
# Here we can rewrite above as A*x = b, where
# A = [[1, 2], 
#      [3, 4]]
# b = [5, 11]
# So, x = A_inv * b
# lets find x:
A = np.array([[1, 2], 
              [3, 4]])
A_inv = inv(A)
b = np.array([5, 11]).T # transpose because b should be 2X1 matrix

x = np.matmul(A_inv,b)
print(x)


Inverse of Matrix:
 [[-2.   1. ]
 [ 1.5 -0.5]]

Verification (A × A_inv should be I):
 [[1. 0.]
 [0. 1.]]
#################################
Inverse of Matrix:
 [[ 0.5        -0.33333333 -0.08333333]
 [ 0.          0.66666667  0.16666667]
 [-0.         -0.33333333  0.16666667]]

Verification (A × A_inv should be I):
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
#################################
[1. 2.]


### Solving Linear Systems
e.g.1: 
```
Solve
1*x1  + 2*x2 = 5
3*x1  + 4*x2 = 11  

=>
Solve Ax = b where:
A = [[1, 2], 
     [3, 4]]
b = [5, 11]
x = [x1, x2]

So, x = A_inverse * b
```


In [21]:
from numpy.linalg import solve

A = np.array([[1, 2], 
              [3, 4]])
b = np.array([5, 11])

x = solve(A, b)
print("\nSolution to Ax = b is x=",x)
print("\nVerification (Ax should equal b):", A @ x) # Should match b


Solution to Ax = b is x= [1. 2.]

Verification (Ax should equal b): [ 5. 11.]


## np.linalg:eigen values and eigen vectors
Uses:
- To reduce the dimensionality of large datasets while preserving the most important variance (information).
- To rank web pages based on their importance.
- To analyze the long-term behavior of dynamic systems (e.g., population growth, vibrations, or circuits).

In [22]:
from numpy.linalg import eig

# How to calculate eigen values/ eigen vestors and also verify for 2X2 matrix
# TAKEN from Lang

# Define a 2x2 matrix
A = np.array([[1, 4], 
              [2, 3]])

eigenvalues, eigenvectors = eig(A)

print(f"Matrix A:\n{A}")
print(f"\nEigenvalues:{eigenvalues}")
print(f"\nEigenvectors (columns):\n{eigenvectors}\n\n")

print(f"Eigen value: {eigenvalues[0]} and its corresponding eigen vector: {eigenvectors[:, 0]}")
print(f"Eigen value: {eigenvalues[1]} and its corresponding eigen vector: {eigenvectors[:, 1]}")

##################################

# First eigenvalue and eigenvector
lambda1 = eigenvalues[0]
v1 = eigenvectors[:, 0]

Av1 = A @ v1
lambda1_v1 = lambda1 * v1

print("\nVerifying First Eigenpair:")
print("A @ v1 =", Av1)
print("λ1 * v1 =", lambda1_v1)
print("Match? ->", np.allclose(Av1, lambda1_v1)) # Returns True if two arrays are element-wise equal within a tolerance.
####################################

# Second eigenvalue and eigenvector
lambda2 = eigenvalues[1]
v2 = eigenvectors[:, 1]

Av2 = A @ v2
lambda2_v2 = lambda2 * v2

print("\nVerifying Second Eigenpair:")
print("A @ v2 =", Av2)
print("λ2 * v2 =", lambda2_v2)
print("Match? ->", np.allclose(Av2, lambda2_v2))


Matrix A:
[[1 4]
 [2 3]]

Eigenvalues:[-1.  5.]

Eigenvectors (columns):
[[-0.89442719 -0.70710678]
 [ 0.4472136  -0.70710678]]


Eigen value: -1.0 and its corresponding eigen vector: [-0.89442719  0.4472136 ]
Eigen value: 5.0 and its corresponding eigen vector: [-0.70710678 -0.70710678]

Verifying First Eigenpair:
A @ v1 = [ 0.89442719 -0.4472136 ]
λ1 * v1 = [ 0.89442719 -0.4472136 ]
Match? -> True

Verifying Second Eigenpair:
A @ v2 = [-3.53553391 -3.53553391]
λ2 * v2 = [-3.53553391 -3.53553391]
Match? -> True


In [23]:
# How to calculate eigen values/ eigen vectors and also verify for 3X3 matrix
# Taken from Lang
from numpy.linalg import eig

# # Set print precision
# np.set_printoptions(precision=3, suppress=True)

# Define a 3x3 matrix
A = np.array([[2, 1, 0],
              [0, 1, -1],
              [0, 2, 4]])

eigenvalues, eigenvectors = eig(A)

print(f"Matrix A:\n{A}")
print(f"\nEigenvalues:\n{np.round(eigenvalues, 3)}")
print(f"\nEigenvectors (columns):\n{np.round(eigenvectors, 3)}\n\n")

print(f"Eigen value: {eigenvalues[0]} and its corresponding eigen vector: {eigenvectors[:, 0]}")
print(f"Eigen value: {eigenvalues[1]} and its corresponding eigen vector: {eigenvectors[:, 1]}")
print(f"Eigen value: {eigenvalues[2]} and its corresponding eigen vector: {eigenvectors[:, 2]}")

##################################

# First eigenpair
lambda1 = eigenvalues[0]
v1 = eigenvectors[:, 0]

Av1 = A @ v1
lambda1_v1 = lambda1 * v1

print("\nVerifying First Eigenpair:")
print("A @ v1 =", np.round(Av1, 3))
print("λ1 * v1 =", np.round(lambda1_v1, 3))
print("Match? ->", np.allclose(Av1, lambda1_v1))

##################################

# Second eigenpair
lambda2 = eigenvalues[1]
v2 = eigenvectors[:, 1]

Av2 = A @ v2
lambda2_v2 = lambda2 * v2

print("\nVerifying Second Eigenpair:")
print("A @ v2 =", np.round(Av2, 3))
print("λ2 * v2 =", np.round(lambda2_v2, 3))
print("Match? ->", np.allclose(Av2, lambda2_v2))

##################################

# Third eigenpair
lambda3 = eigenvalues[2]
v3 = eigenvectors[:, 2]

Av3 = A @ v3
lambda3_v3 = lambda3 * v3

print("\nVerifying Third Eigenpair:")
print("A @ v3 =", np.round(Av3, 3))
print("λ3 * v3 =", np.round(lambda3_v3, 3))
print("Match? ->", np.allclose(Av3, lambda3_v3))


Matrix A:
[[ 2  1  0]
 [ 0  1 -1]
 [ 0  2  4]]

Eigenvalues:
[2. 2. 3.]

Eigenvectors (columns):
[[ 1.     1.     0.408]
 [ 0.    -0.     0.408]
 [ 0.     0.    -0.816]]


Eigen value: 2.0 and its corresponding eigen vector: [1. 0. 0.]
Eigen value: 2.0 and its corresponding eigen vector: [ 1.0000000e+00 -4.4408921e-16  4.4408921e-16]
Eigen value: 3.0 and its corresponding eigen vector: [ 0.40824829  0.40824829 -0.81649658]

Verifying First Eigenpair:
A @ v1 = [2. 0. 0.]
λ1 * v1 = [2. 0. 0.]
Match? -> True

Verifying Second Eigenpair:
A @ v2 = [ 2. -0.  0.]
λ2 * v2 = [ 2. -0.  0.]
Match? -> True

Verifying Third Eigenpair:
A @ v3 = [ 1.225  1.225 -2.449]
λ3 * v3 = [ 1.225  1.225 -2.449]
Match? -> True


## (OPTIONAL) SVD, Rank
Singular Value Decomposition (SVD) is a powerful matrix factorization technique that breaks down any real or complex matrix A into three constituent matrices:

A = U * S * Vt

Where:

U is an orthogonal matrix (left singular vectors)

S (Sigma) is a diagonal matrix of singular-values (non-negative, usually ordered from largest to smallest)

Vt is the transpose of an orthogonal matrix (right singular vectors)

In [24]:
from numpy.linalg import svd

A = np.array([[1, 2],
              [3, 4],
              [5, 6]])

U, Sing_val, Vt = svd(A)
print("\nU matrix:")
print(U)

print("\nSingular values:")
print(Sing_val)
# Create Sigma diagonal matrix from singular values
Sigma = np.zeros(A.shape)
Sigma[:len(Sing_val), :len(Sing_val)] = np.diag(Sing_val)
print("\nSigma matrix from singular values:")
print(Sigma)

print("\nV transpose matrix:")
print(Vt)


# Reconstruct A
A_reconstructed = U @ Sigma @ Vt
print("\nReconstructed matrix:")
print(A_reconstructed)

print("###################################")
from numpy.linalg import matrix_rank

E = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

rank = matrix_rank(E)
print("\nMatrix rank:")
print(rank)  # Will be 2 (linearly dependent rows)


U matrix:
[[-0.2298477   0.88346102  0.40824829]
 [-0.52474482  0.24078249 -0.81649658]
 [-0.81964194 -0.40189603  0.40824829]]

Singular values:
[9.52551809 0.51430058]

Sigma matrix from singular values:
[[9.52551809 0.        ]
 [0.         0.51430058]
 [0.         0.        ]]

V transpose matrix:
[[-0.61962948 -0.78489445]
 [-0.78489445  0.61962948]]

Reconstructed matrix:
[[1. 2.]
 [3. 4.]
 [5. 6.]]
###################################

Matrix rank:
2
