# changing the shape of arrays
- vstack

In [19]:
import numpy as np

### vstack()
- **stack arrays row-wise (vertically) to create a single array**.
- combine smaller arrays into a bigger one.

In [25]:
# I want to take four 1D array of shape = 5 and turn it into 2D array of shape 4X5:

x1 = np.array([10, 20, 30, 40, 50])  
x2 = np.array([20, 40, 60, 80, 100])
x3 = np.array([18, 40, 50, 20,  30]) 
x4 = np.array([90, 82, 55, 40, 20]) 

x = np.vstack((x1, x2, x3, x4))
print(x.shape)
print(x)

(4, 5)
[[ 10  20  30  40  50]
 [ 20  40  60  80 100]
 [ 18  40  50  20  30]
 [ 90  82  55  40  20]]


In [26]:
x1 = np.array([10, 20, 30, 40, 50])  
x2 = np.array([20, 40, 60, 80, 100])
x3 = np.array([18, 40, 50, 20, 30]) 
x4 = np.array([90, 82, 55, 40, 20]) 

x = np.array([x1, x2, x3, x4])   # shape (4,5)

print(x.shape)  # (4, 5)
print(x)

(4, 5)
[[ 10  20  30  40  50]
 [ 20  40  60  80 100]
 [ 18  40  50  20  30]
 [ 90  82  55  40  20]]
