# changing the shape of arrays

In [2]:
import numpy as np

## Transpose
- For 2D arrays (matrices), it swaps rows and columns.
- For n-dimensional arrays, it reorders the dimensions based on the given axes.

### Note
- You can transpose using **np.transpose(a, axes=None)**
- Or you can use **array.T** bit it does not give option to select axis. This is best for 2D array


### Application:
- Preparing data for algorithms like matrix multiplication or PCA (Principal Component Analysis), which require certain shape conventions.

In [3]:
# Transpose for 2D: nXm matrix becomes mXn matrix 

# Using x.T. It is best for 2D and commonly used in 2D
# If shape of x is 2X3. Then shape of x.T is 3X2
x = np.array([
    [1, 2, 3], 
    [4, 5 ,6]] 
)
print(x)

transpose = x.T
print(transpose)  
print("####################")

# If shape of x is 3X2. Then shape of x.T is 2X3
x = np.array([[1,2],
              [3,4],
              [5,6]]
)
print(x)

transpose = x.T
print(transpose)  
print("####################")

# Note that taking the transpose of a rank 1 array does nothing:
v = np.array([1,2,3])
print(v)    
print(v.T)  

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]
####################
[[1 2]
 [3 4]
 [5 6]]
[[1 3 5]
 [2 4 6]]
####################
[1 2 3]
[1 2 3]


In [4]:
# Transpose for 2D: nXm matrix becomes mXn matrix 

# Using np.transpose()

# If shape of x is 2X3. Then shape of x.T is 3X2
x = np.array([
    [1, 2, 3], 
    [4, 5 ,6]] 
)
print(x)

transpose = np.transpose(x)
print(transpose)  
print("####################")

# If shape of x is 3X2. Then shape of x.T is 2X3
x = np.array([[1,2],
              [3,4],
              [5,6]]
)
print(x)

transpose = np.transpose(x)
print(transpose)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]
####################
[[1 2]
 [3 4]
 [5 6]]
[[1 3 5]
 [2 4 6]]


In [10]:
# ADVANCED: transpose of 3D and higher

# Create a 3D array of shape 2X3X4
a = np.arange(24).reshape(2, 3, 4) 
print("a:\n", a)
print(a.shape)  # (2, 3, 4)

# Default transpose: reverses axes order
b = np.transpose(a)
print("b:\n", b)
print(b.shape)  # (4, 3, 2)

# Custom axis order
c = np.transpose(a, axes=(1, 0, 2))
print("c:\n", c)
print(c.shape)  # (3, 2, 4)

a:
 [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
(2, 3, 4)
b:
 [[[ 0 12]
  [ 4 16]
  [ 8 20]]

 [[ 1 13]
  [ 5 17]
  [ 9 21]]

 [[ 2 14]
  [ 6 18]
  [10 22]]

 [[ 3 15]
  [ 7 19]
  [11 23]]]
(4, 3, 2)
c:
 [[[ 0  1  2  3]
  [12 13 14 15]]

 [[ 4  5  6  7]
  [16 17 18 19]]

 [[ 8  9 10 11]
  [20 21 22 23]]]
(3, 2, 4)


### vstack()
- **stack arrays row-wise (vertically) to create a single array**.
- combine smaller arrays into a bigger one.

In [18]:
x1 = np.array([10, 20, 30, 40, 50])  
x2 = np.array([20, 40, 60, 80, 100])
x3 = np.array([18, 40, 50, 20,  30]) 
x4 = np.array([90, 82, 55, 40, 20]) 

x = np.vstack((x1, x2, x3, x4))
print(x)

[[ 10  20  30  40  50]
 [ 20  40  60  80 100]
 [ 18  40  50  20  30]
 [ 90  82  55  40  20]]
