### Topics covered:
- stat operations: mean, median, min, max, std_dev, var, percentile, describe, corrcoef, cov,


In [3]:
import numpy as np

# STATS 

In [25]:
import numpy as np

# data = np.array([12, 15, 14, 13, 20, 22, 25, 21, 19, 18, 17, 230000]) # Monthly sales data in 1000s
# data = np.array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])
# data = np.array([4, 3, 5, 6, 7, 3, 5, 6, 4, 5])
data = np.array([1, 1, 0, 0, 5, 9, 9,10, 10, 5])


# Calculate statistics
mean_value = np.mean(data) # TODO
print("Mean:", mean_value)

variance = np.var(data)
print("Variance:", variance)

std_deviation = np.std(data)
print("Standard Deviation:", std_deviation) # Sales typically vary ±$std_deviationK from the mean.

median_value = np.median(data)
print("Median:", median_value) # Half the months are above/below this.


min_value = np.min(data)
print("Minimum:", min_value)
arg_min = np.argmin(data)
print("arg_min:", arg_min)


max_value = np.max(data)
print("Maximum:", max_value)
arg_max = np.argmax(data)
print("arg_max:", arg_max)

sorted_idx = np.argsort(data) # OPTIONAL
print("sorted_idx:", sorted_idx)

percentile_25 = np.percentile(data, 25)
print("25th Percentile:", percentile_25)

percentile_75 = np.percentile(data, 75)
print("75th Percentile:", percentile_75)

Mean: 5.0
Variance: 16.4
Standard Deviation: 4.049691346263317
Median: 5.0
Minimum: 0
arg_min: 2
Maximum: 10
arg_max: 7
sorted_idx: [2 3 0 1 4 9 5 6 7 8]
25th Percentile: 1.0
75th Percentile: 9.0


In [26]:
# APPLICATION:
# generate a random sample of size 50 with a mean of 107 using NumPy

np.random.seed(42)  

# Set the desired parameters
sample_size = 50
desired_mean = 107

# Generate random values (e.g., from a normal distribution)
# We'll generate a sample with mean 0, then shift it to desired mean
random_sample = np.random.normal(loc=0, scale=10, size=sample_size)

# Shift the sample to have the desired mean
adjusted_sample = random_sample - np.mean(random_sample) + desired_mean
adjusted_sample = np.round(adjusted_sample,1).astype(int)

# Print the sample and its mean
print("Sample values:", adjusted_sample)
print("Sample mean:", np.mean(adjusted_sample))


Sample values: [114 107 115 124 106 106 125 116 104 114 104 104 111  90  92 103  99 112
 100  95 123 107 109  95 103 110  97 113 103 106 103 127 109  98 117  97
 111  89  96 111 116 111 108 106  94 102 104 119 112  91]
Sample mean: 106.56


In [30]:
# Application1 : finding relation between 2 variable
import numpy as np
x1 = np.array([1, 2, 3, 4, 5]) # game_hours
x2 = np.array([95, 90, 85, 80, 75]) # exam_scores

# compute covariance matrix
cov_matrix = np.cov(x1, x2)

print(f"Covariance matrix: \n{cov_matrix}")
print(f"Covariance between StudyHours and ExamScore: {cov_matrix[0,1]}")

print("###################")
corr_matrix = np.corrcoef(x1, x2)
print(f"corr_matrix between x1 and x2: \n{corr_matrix}")


Covariance matrix: 
[[  2.5 -12.5]
 [-12.5  62.5]]
Covariance between StudyHours and ExamScore: -12.5
###################
corr_matrix between x1 and x2: 
[[ 1. -1.]
 [-1.  1.]]


In [31]:
# Application: finding relation between  many variable
import numpy as np
x1 = np.array([10, 20, 30, 40, 50])  # resistance with I=2
x2 = np.array([20, 40, 60, 80, 100]) # voltage measured via a top quality voltmeter
x3 = np.array([18, 40, 50, 20,  30]) # voltage measured via a sub quality voltmeter
x4 = np.array([90, 82, 55, 40, 20]) #  some other var with -ve correlation

# stack and compute covariance
X = np.vstack((x1, x2, x3, x4))
cov_matrix = np.cov(X)
print("Covariance matrix:\n", cov_matrix)
print("##################")

X = np.vstack((x1, x2, x3, x4))
corr_matrix = np.corrcoef(X)
print(f"corr_matrix: \n{corr_matrix}")

Covariance matrix:
 [[ 250.   500.    10.  -455. ]
 [ 500.  1000.    20.  -910. ]
 [  10.    20.   182.8   -4.8]
 [-455.  -910.    -4.8  843.8]]
##################
corr_matrix: 
[[ 1.          1.          0.04677803 -0.99065317]
 [ 1.          1.          0.04677803 -0.99065317]
 [ 0.04677803  0.04677803  1.         -0.01222175]
 [-0.99065317 -0.99065317 -0.01222175  1.        ]]


## package stat and its methods

In [ ]:
# SKIP
from scipy.stats import mode # NumPy does not have a built-in mode()

# how to calculate mode: the most frequent item
# Use Cases:
# Product reviews:	Find the most common rating
# Voting systems:	Determine the most popular choice
# Health surveys:	Identify most frequently reported symptom
# Transport:	Find the most common route or time taken

arr = np.array([1, 2, 2, 3, 4, 4, 4, 5, 5, 4, 4]) # rating for a certain  product

mode_result = mode(arr, keepdims=True)
print("Mode:", mode_result.mode[0]) # most common result
print("Count:", mode_result.count[0])