# NumPy
Numpy is the core library for **scientific computing in Python**. It provides a **high-performance multidimensional array object, and tools for working with these arrays**.

### Topics covered:
- creating/accessing/modifying arrays
- np methods to create arrays: zeros , ones, full, eye, random, randomint, arrange
- array indexing / slicing: integer array indexing, boolean array indexing

## Arrays
A numpy array is a grid of values, all of the same type, and is indexed by a tuple of nonnegative integers. **The number of dimensions is the rank of the array**; the shape of an array is a tuple of integers giving the size of the array along each dimension.

A rank 1 array (also known as a 1-dimensional array) is essentially a list of values.

We can initialize numpy arrays from nested Python lists, and access elements using square brackets:

In [2]:
import numpy as np

In [ ]:
# create an array of shape (3)
a = np.array([1, 2, 3])   # Create a rank 1(i.e. 1D) array
# a = np.array([1, 2, 3], dtype=np.int16)   # MORE ON dtype later

print(type(a), a.ndim)    # <class 'numpy.ndarray'> 1
print(a.shape)            # (3,)
print(a)
############################

# create an array of shape (2,3)
b = np.array([[1,2,3],
              [4,5,6]]
)    # Create a rank 2 array
print(type(b), b.ndim)    # <class 'numpy.ndarray'> 2
print(b.shape)            # (2, 3)
print(b)

b = np.array([[1,2,3],
              [4,5,6]]
)    # Create a rank 2 array
print(type(b), b.ndim)    # <class 'numpy.ndarray'> 2
print(b.shape)            # (2, 3)
print(b)

# Creating a 3D array with shape (2, 3, 5)
b = np.array([
    [  # First block (depth index 0)
        [1, 2, 3, 4, 5],      # row1
        [6, 7, 8, 9, 10],     # row2
        [11, 12, 13, 14, 15]  # row3
    ],
    [  # Second block (depth index 1)
        [16, 17, 18, 19, 20], # row1
        [21, 22, 23, 24, 25], # row2
        [26, 27, 28, 29, 30]  # row3
    ]
])
print(type(b), b.ndim)    # <class 'numpy.ndarray'> 3
print(b.shape)            # (2, 3, 5)
print(b)

# create an array of shape (2,2,2)
b = np.array([
    [ # First block (depth index 0)
        [1, 2],
        [3, 4]
    ],
    [ # Second block (depth index 1)
        [5, 6],
        [7, 8]
    ]
])
print(type(b), b.ndim)    # <class 'numpy.ndarray'> 3
print(b.shape)            # (2, 2, 2)
print(b)


<class 'numpy.ndarray'> 1
(3,)
[1 2 3]
<class 'numpy.ndarray'> 2
(2, 3)
[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'> 2
(2, 3)
[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'> 3
(2, 3, 5)
[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]]

 [[16 17 18 19 20]
  [21 22 23 24 25]
  [26 27 28 29 30]]]
<class 'numpy.ndarray'> 3
(2, 2, 2)
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
# access elements and modify single element

#access 1D array and modify elements
a = np.array([1, 2, 3])   # Create a rank 1(i.e. 1D) array
print(a[2])
print(a[0], a[1], a[2])   # Prints "1 2 3"
a[0] = 5                  # Change an element of the array

#access 2D array and modify elements
# Use: b[row_index][column_index]
# or   b[row_index, column_index]
b = np.array([[1,2,3],
              [4,5,6]]
)    # Create a rank 2 array
print(type(b), b.ndim)
print(b.shape)

print(b[0][0])
print(b[0, 0])

print(b[0][0], b[0][1], b[1][0])   # Prints "1 2 4"
print(b[0, 0], b[0, 1], b[1, 0])   # Prints "1 2 4"

b[0,2] = 9 # change an element
print(b)

#access 3D array and modify elements
# Use: b[block_index][row_index][column_index]
# or   b[block_index, row_index, column_index]
b = np.array([
    [  # First block (depth index 0)
        [1, 2, 3, 4, 5],      # row1
        [6, 7, 8, 9, 10],     # row2
        [11, 12, 13, 14, 15]  # row3
    ],
    [  # Second block (depth index 1)
        [16, 17, 18, 19, 20], # row1
        [21, 22, 23, 24, 25], # row2
        [26, 27, 28, 29, 30]  # row3
    ]
])
print(type(b), b.ndim)    # <class 'numpy.ndarray'> 3
print(b.shape)            # (2, 3, 5)
print(b[0][2][0])
print(b[0, 2, 0])

print(b[0][2][0], b[0][2][1], b[0] [2] [2])   # print '11 12 13'
print(b[0, 2, 0], b[0, 2, 1], b[0, 2, 2])   # print '11 12 13'

3
1 2 3
<class 'numpy.ndarray'> 2
(2, 3)
1
1
1 2 4
1 2 4
[[1 2 9]
 [4 5 6]]
<class 'numpy.ndarray'> 3
(2, 3, 5)
11
11
11 12 13
11 12 13


**Numpy also provides many functions to create arrays**

In [ ]:
a = np.zeros(3) 
print(a)


a = np.zeros((2,2))   # Create an array of all zeros
print(a)              # Prints "[[ 0.  0.]
                      #          [ 0.  0.]]"
print(type(a), a.ndim)
print(a.shape)

a = np.zeros((3,3))
print(a)
print(type(a), a.ndim)
print(a.shape)

a = np.zeros((3,5))
print(a)
print(type(a), a.ndim)
print(a.shape)


[[0. 0.]
 [0. 0.]]
<class 'numpy.ndarray'> 2
(2, 2)
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
<class 'numpy.ndarray'> 2
(3, 3)
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
<class 'numpy.ndarray'> 2
(3, 5)


In [ ]:
b = np.ones((1,2))    # Create an array of all ones
print(b)              # Prints "[[ 1.  1.]]"

a = np.ones((3,5))
print(a)

a = np.full((3,4), fill_value=7)
a = np.full((2,2), 7)  # Create a constant array
print(a)               # Prints "[[ 7.  7.]
                       #          [ 7.  7.]]"
a = np.full((4,2), 7)
print(a)

[[1. 1.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[7 7]
 [7 7]]
[[7 7]
 [7 7]
 [7 7]
 [7 7]]


In [ ]:
d = np.eye(2)         # Create a 2x2 identity matrix
print(d)              # Prints "[[ 1.  0.]
                      #          [ 0.  1.]]"

d = np.eye(3)
print(d)

d = np.eye(3, 5)
print(d)

[[1. 0.]
 [0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


In [4]:
e = np.random.random((3))  # Create an 1Darray of size 3 filled with random values
print(e)
print(type(e), e.shape)


e = np.random.random((2,2))  # Create an array filled with random values
print(e)                     # Might print "[[ 0.91940167  0.08143941]
                             #               [ 0.68744134  0.87236687]]"
print(type(e), e.shape)

e = np.random.random((2,4))  # Create an array filled with random values
print(e)
print(type(e), e.shape)

# Generate a 1D array with 3 elements with random integers between -10 (inclusive) and 15 (exclusive)
e = np.random.randint(-10, 15, size=3)
print(e)
print(type(e), e.shape)


# Generate a 3x3 matrix with random integers between -10 (inclusive) and 15 (exclusive)
random_data = np.random.randint(-10, 15, size=(3, 3))
print("Random Matrix:\n", random_data)

[0.83828646 0.4220447  0.73288844]
<class 'numpy.ndarray'> (3,)
[[0.05688958 0.94210922]
 [0.63063407 0.77615941]]
<class 'numpy.ndarray'> (2, 2)
[[0.40752374 0.08326445 0.88942241 0.07973494]
 [0.21946751 0.04269711 0.80434401 0.67485856]]
<class 'numpy.ndarray'> (2, 4)
[13 10 -8]
<class 'numpy.ndarray'> (3,)
Random Matrix:
 [[ 8 11  8]
 [-8 -9  0]
 [11 -1 13]]


In [ ]:
# arange

# Example 1: Basic usage with start and stop
arr = np.arange(5)  # Creates an array from 0 to 4
print("Example 1 - Array from 0 to 4:")
print(arr)

# Example 2: Specifying start and stop
arr = np.arange(2, 10)  # Creates an array from 2 to 9
print("\nExample 2 - Array from 2 to 9:")
print(arr)

# Example 3: Specifying start, stop, and step
arr = np.arange(1, 10, 2)  # Creates an array from 1 to 9 with a step of 2
print("\nExample 3 - Array from 1 to 9 with step of 2:")
print(arr)

# Example 4: Using a negative step
arr = np.arange(10, 0, -2)  # Creates an array from 10 to 2 with a step of -2
print("\nExample 4 - Array from 10 to 2 with step of -2:")
print(arr)

# Example 5: Specifying dtype
arr = np.arange(0, 1, 0.1, dtype=float)  # Creates an array of floats from 0 to 0.9
print("\nExample 5 - Array of floats from 0 to 0.9:")
print(arr)

Example 1 - Array from 0 to 4:
[0 1 2 3 4]

Example 2 - Array from 2 to 9:
[2 3 4 5 6 7 8 9]

Example 3 - Array from 1 to 9 with step of 2:
[1 3 5 7 9]

Example 4 - Array from 10 to 2 with step of -2:
[10  8  6  4  2]

Example 5 - Array of floats from 0 to 0.9:
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


## Array indexing
Numpy offers several ways to index into arrays.

**Slicing**: Similar to Python lists, numpy arrays can be sliced. Since arrays may be multidimensional, you must **specify a slice for each dimension of the array**:

In [ ]:
# Create the following rank 2 array with shape (3, 4)
a = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10,11,12]
             ])

# Use slicing to pull out the subarray consisting of the first 2 rows(i.e. rows 0 and 1)
# and columns 1 and 2; b is the following array of shape (2, 2):
# [[2 3]
#  [6 7]]
b = a[:2, 1:3]

# A slice of an array is a view into the same data, so modifying it
# will modify the original array.
print(a[0, 1])   # Prints "2"
b[0, 0] = 77     # b[0, 0] is the same piece of data as a[0, 1]
print(a[0, 1])   # Prints "77"
print(a)

2
77
[[ 1 77  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


You can also mix integer indexing with slice indexing. However, doing so will yield an array of lower rank than the original array.

In [ ]:
# Create the following rank 2 array with shape (3, 4)
a = np.array([[1,2,3,4],
              [5,6,7,8],
              [9,10,11,12]]
)

# Two ways of accessing the data in the middle row of the array.
# Mixing integer indexing with slices yields an array of lower rank,
# while using only slices yields an array of the same rank as the original array:
row_r1 = a[1, :]    # Rank 1 view of the second row of a
row_r2 = a[1:2, :]  # Rank 2 view of the second row of a
print(row_r1, row_r1.shape)  # Prints "[5 6 7 8] (4,)"
print(row_r2, row_r2.shape)  # Prints "[[5 6 7 8]] (1, 4)"

# We can make the same distinction when accessing columns of an array:
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print(col_r1, col_r1.shape)  # Prints "[ 2  6 10] (3,)"
print(col_r2, col_r2.shape)  # Prints "[[ 2]
                             #          [ 6]
                             #          [10]] (3, 1)"

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)


Integer array indexing:
- When you index into numpy arrays using slicing, the resulting array view will always be a subarray of the original array.
- In contrast, integer array indexing allows you to construct arbitrary arrays using the data from another array.
Here is an example:

In [ ]:
a = np.array([[1, 2],
              [3, 4],
              [5, 6]]
)

# An example of integer array indexing.
# The returned array will have shape (3,) and

# The above example of integer array indexing is equivalent to this:
print(np.array([a[0, 0], a[1, 1], a[2, 0]]))  # Prints "[1 4 5]"
# print(a[[0, 1, 2], [0, 1, 0]])  # Prints "[1 4 5]"


[1 4 5]
[2 2]


One useful trick with integer array indexing is selecting or mutating one element from each row of a matrix:

In [5]:
# Create a new array from which we will select elements
a = np.array([[1,2,3],
              [4,5,6],
              [7,8,9],
              [10, 11, 12]]
)

print(f"a: \n{a}")

# Create an array of col_indices: 0, 2, 0, 1
col_indices = np.array([0, 2, 0, 1])

# Select one element from each row of a using the indices in col_indices
print(a[np.arange(4), col_indices])  # Prints "[ 1  6  7 11]"

# Mutate one element from each row of a using the indices in col_indices
a[np.arange(4), col_indices] += 10

print(a)  # prints "array([[11,  2,  3],
          #                [ 4,  5, 16],
          #                [17,  8,  9],
          #                [10, 21, 12]])

a: 
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[ 1  6  7 11]
[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


**Boolean array indexing**: Boolean array indexing lets you pick out arbitrary elements of an array. Frequently this type of indexing is used to select the elements of an array that satisfy some condition.

Here is an example:

In [ ]:
a = np.array([[1,2],
              [3, 4],
              [5, 6]]
)

bool_idx = (a > 2)   # Find the elements of a that are bigger than 2;
                     # this returns a numpy array of Booleans of the same
                     # shape as a, where each slot of bool_idx tells
                     # whether that element of a is > 2.

print(bool_idx)      # Prints "[[False False]
                     #          [ True  True]
                     #          [ True  True]]"

# We use boolean array indexing to construct a rank 1 array
# consisting of the elements of a corresponding to the True values
# of bool_idx
print(a[bool_idx])  # Prints "[3 4 5 6]"

# We can do all of the above in a single concise statement:
print(a[a > 2])     # Prints "[3 4 5 6]"

[[False False]
 [ True  True]
 [ True  True]]
[3 4 5 6]
[3 4 5 6]
