### Topics covered:
- filtering
- where()

In [3]:
# !pip install numpy

In [1]:
import numpy as np

In [ ]:
# On 1D

cont = [4, 7, 2, 3, 9, 3, 6, 2, 1, 7] # water contaminant reading
a = np.array(cont)

# Filter: select elements equal to 3
mask = (a == 3)
# print(mask)
print(a[mask]) 
print(len(a[mask])) # gives count
################################

# Filter: All elements not equal to 3
mask = (a != 3)
print(a[mask]) 
################################

# Filter: All elem > 2 # UNHEALTHY water
mask = (a > 2)
print(a[mask])     
################################

# Filter: All elem > 2 and < 5 # MODERATE
mask = (a > 2) & (a < 5)
print(a[mask]) 
################################

# select elements less than 2 or greater than 4:
mask = (a < 2) | (a > 4)
print(a[mask])
################################

[3 3]
2
[4 7 2 9 6 2 1 7]
[4 7 3 9 3 6 7]
[4 3 3]
[7 9 6 1 7]


In [6]:
# filter and replace: Replace values less than 20 with 0
arr = np.array([5, 12, 18, 25, 30, 3, 45])


arr[arr < 20] = 0
print(arr) 

[ 0  0  0 25 30  0 45]


### where()
- np.where():  find the indices of elements in an array that satisfy certain condition. It can also be used to create new arrays based on conditions
- np.where(condition, x, y)  → Returns x if condition is True, else y.

In [4]:
arr = np.array([70, 20, 50, 20, 50, 10, 30])

# Indices where condition is true
indices = np.where(arr > 25)
print(indices)      # (array([2, 3, 4]),)
print(arr[indices]) # [30 40 50]

(array([0, 2, 4, 6], dtype=int64),)
[70 50 50 30]


In [2]:
# where()

# Application1: Assigning Letter Grades Based on Scores
scores = np.array([78, 45, 62, 33, 90, 50]) # Student scores
results = np.where(scores >= 50, "Pass", "Fail") # Use np.where to assign "Pass" or "Fail"

print("Scores:", scores)
print("Results:", results)

print("*****************************")
# Application2: Daily temperatures (°C) recorded over a week
temperatures = np.array([28, 33, 31, 25, 29, 35, 30])

temp_classification = np.where(temperatures > 30, 'Greater than 30', '30 or less')

print("Temperature readings:", temperatures)
print("Classification:", temp_classification)
print("^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^")

# Create a 2D NumPy array
# Temperatures (°C) recorded hourly in 3 rooms over 4 hours
temps = np.array([
    # Room1, Room2, Room3
    [22, 26, 24],  # Hour 1
    [23, 27, 26],  # Hour 2
    [25, 28, 23],  # Hour 3
    [21, 24, 27]   # Hour 4
])

# Flag temperatures above 25°C as "Alert", else "Normal"
status = np.where(temps > 25, "Alert", "Normal")

print("Temperature readings:\n", temps)
print("\nStatus:\n", status)


Scores: [78 45 62 33 90 50]
Results: ['Pass' 'Fail' 'Pass' 'Fail' 'Pass' 'Pass']
*****************************
Temperature readings: [28 33 31 25 29 35 30]
Classification: ['30 or less' 'Greater than 30' 'Greater than 30' '30 or less'
 '30 or less' 'Greater than 30' '30 or less']
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Temperature readings:
 [[22 26 24]
 [23 27 26]
 [25 28 23]
 [21 24 27]]

Status:
 [['Normal' 'Alert' 'Normal']
 ['Normal' 'Alert' 'Alert']
 ['Normal' 'Alert' 'Normal']
 ['Normal' 'Normal' 'Alert']]
