### Topics covered:
- math: add, subtract, multiply, divide
- math: square, root, power, log, exp, round, ceil, floor,
- math: prod, cumsum, cumprod, diff
- flatten / reshape
- unique
- dot product, determinant, inverse, sum, transpose
- eigen values, eigen vectors

- stat operations: mean, median, min, max, std_dev, var, percentile, describe, corrcoef, cov,

- isin, where
- set operations

## Array math
Basic mathematical functions operate elementwise on arrays, and are available both as operator overloads and as functions in the numpy module:

In [18]:
import numpy as np

In [19]:
x = np.array([[1,2],
              [3,4]], dtype=np.float64
)
y = np.array([[5,6],
              [7,8]], dtype=np.float64
)

# Elementwise sum; both produce the array
# [[ 6.0  8.0]
#  [10.0 12.0]]
print(x + y)
print(np.add(x, y))

# Elementwise difference; both produce the array
# [[-4.0 -4.0]
#  [-4.0 -4.0]]
print(x - y)
print(np.subtract(x, y))

# Elementwise product; both produce the array
# [[ 5.0 12.0]
#  [21.0 32.0]]
print(x * y)
print(np.multiply(x, y))

# Elementwise division; both produce the array
# [[ 0.2         0.33333333]
#  [ 0.42857143  0.5       ]]
print(x / y)
print(np.divide(x, y))


[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]
[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]
[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]
[[0.2   0.333]
 [0.429 0.5  ]]
[[0.2   0.333]
 [0.429 0.5  ]]


In [20]:
x = np.array([[1,2],
              [3,4]], dtype=np.float64
)

# Elementwise square root; produces the array
# [[ 1.          1.41421356]
#  [ 1.73205081  2.        ]]
print(np.sqrt(x))

# Power
power_result = np.power(x, 2)  # Raises each element to the power of 2
print("Power:", power_result)

# Exponential
exp_result = np.exp(x)  # Computes e^x for each element
print("Exponential:", exp_result)

# Logarithm
log_result = np.log(x)  # Computes the natural logarithm
print("Natural Logarithm:", log_result)

log10_result = np.log10(x)  # Computes the base-10 logarithm
print("Base-10 Logarithm:", log10_result)

# Rounding Functions
floor_result = np.floor(x + 0.5)  # Rounds down
print("Floor:", floor_result)

ceil_result = np.ceil(x + 0.5)    # Rounds up
print("Ceil:", ceil_result)

round_result = np.round(x + 0.5)   # Rounds to nearest integer
print("Round:", round_result)

[[1.    1.414]
 [1.732 2.   ]]
Power: [[ 1.  4.]
 [ 9. 16.]]
Exponential: [[ 2.718  7.389]
 [20.086 54.598]]
Natural Logarithm: [[0.    0.693]
 [1.099 1.386]]
Base-10 Logarithm: [[0.    0.301]
 [0.477 0.602]]
Floor: [[1. 2.]
 [3. 4.]]
Ceil: [[2. 3.]
 [4. 5.]]
Round: [[2. 2.]
 [4. 4.]]


In [21]:

a = np.array([2, 3, 4])
b = np.array([3, 2, 1])

result = np.power(a, b)
print(result)  # Output: [8 9 4] → [2^3, 3^2, 4^1]
##########################################

a = np.array([10, 20, 30])
b = np.array([3, 7, 8])

# rem1 = np.remainder(a, b)
rem2 = np.mod(a, b)

# print(rem1)  # Output: [1 6 6]
print(rem2)  # Output: [1 6 6]

result = np.floor_divide(a, b)
print(result)  # Output: [3 2 3] → [10//3, 20//7, 30//8]


[8 9 4]
[1 6 6]
[3 2 3]


In [22]:
arr = np.array([1, 2, 3, 4])

result = np.prod(arr)
print(result)  # Output: 24 → 1*2*3*4

result = np.cumsum(arr)
print(result)  # Output: [ 1  3  6 10]

result = np.cumprod(arr)
print(result)  # Output: [ 1  2  6 24]
####################################
arr = np.array([10, 15, 20, 25])

result = np.diff(arr)
print(result)  # Output: [5 5 5] → [15-10, 20-15, 25-20]

####################################
arr2 = np.array([[1, 2],
                 [3, 4]]
)
print(np.prod(arr2, axis=0))  # Output: [3 8] → column-wise product


24
[ 1  3  6 10]
[ 1  2  6 24]
[5 5 5]
[3 8]


### flatten / reshape
**flatten**: Convert a multi-dimensional array into a one-dimensional array. This is particularly useful when you want to simplify the structure of your data for processing or analysis.

The opposite of the flatten() operation in NumPy is **reshape()**, which reshapes the array to a new shape of the array, as long as the total number of elements remains the same.

In [23]:
# lets flatten an array
# Create a 2D NumPy array (matrix)
array_2d = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]])

print("Original 2D Array:")
print(array_2d)

# Flatten the 2D array into a 1D array
flattened_array = array_2d.flatten()

print("\nFlattened Array:")
print(flattened_array)

Original 2D Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Flattened Array:
[1 2 3 4 5 6 7 8 9]


In [24]:
# lets reshape a flattened array

# Create a flattened array of size 18
flattened_array = np.arange(18)  # This creates an array with values from 0 to 17
print("Flattened Array:")
print(flattened_array)

# Reshape into different sizes

# 1. Reshape to 2D array of shape (2, 9)
reshaped_2d_2x9 = flattened_array.reshape(2, 9)
print("\nReshaped Array (2x9):")
print(reshaped_2d_2x9)
print(type(reshaped_2d_2x9), reshaped_2d_2x9.ndim) # <class 'numpy.ndarray'> 2
print(reshaped_2d_2x9.shape) # (2, 9)          


# 2. Reshape to 2D array of shape (3, 6)
reshaped_2d_3x6 = flattened_array.reshape(3, 6)
print("\nReshaped Array (3x6):")
print(reshaped_2d_3x6)

# 3. Reshape to 2D array of shape (6, 3)
reshaped_2d_6x3 = flattened_array.reshape(6, 3)
print("\nReshaped Array (6x3):")
print(reshaped_2d_6x3)

# 4. Reshape to 3D array of shape (2, 3, 3)
reshaped_3d_2x3x3 = flattened_array.reshape(2, 3, 3)
print("\nReshaped Array (2x3x3):")
print(reshaped_3d_2x3x3)

# 5. Reshape to 3D array of shape (3, 2, 3)
reshaped_3d_3x2x3 = flattened_array.reshape(3, 2, 3)
print("\nReshaped Array (3x2x3):")
print(reshaped_3d_3x2x3)

# 6. Reshape to 1D array (keeping it the same)
reshaped_1d = flattened_array.reshape(18)
print("\nReshaped Array (1D, same as original):")
print(reshaped_1d)

Flattened Array:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]

Reshaped Array (2x9):
[[ 0  1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16 17]]
<class 'numpy.ndarray'> 2
(2, 9)

Reshaped Array (3x6):
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]

Reshaped Array (6x3):
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]

Reshaped Array (2x3x3):
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]]

Reshaped Array (3x2x3):
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]]]

Reshaped Array (1D, same as original):
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]


In [25]:
# find uniques values

# Create a 2D NumPy array
array_2d = np.array([[1, 2, 3],
                     [4, 2, 6],
                     [1, 8, 3],
                     [4, 5, 6]])

print("Original 2D Array:")
print(array_2d)

# Find unique values across the entire array
unique_values = np.unique(array_2d)
print("\nUnique values in the entire array:")
print(unique_values)

# Find unique values in each column (axis=0)
unique_columns = [np.unique(array_2d[:, col]) for col in range(array_2d.shape[1])]
print("\nUnique values in each column:")
for i, unique in enumerate(unique_columns):
    print(f"Column {i}: {unique}")

# Find unique values in each row (axis=1)
unique_rows = [np.unique(array_2d[row, :]) for row in range(array_2d.shape[0])]
print("\nUnique values in each row:")
for i, unique in enumerate(unique_rows):
    print(f"Row {i}: {unique}")

Original 2D Array:
[[1 2 3]
 [4 2 6]
 [1 8 3]
 [4 5 6]]

Unique values in the entire array:
[1 2 3 4 5 6 8]

Unique values in each column:
Column 0: [1 4]
Column 1: [2 5 8]
Column 2: [3 6]

Unique values in each row:
Row 0: [1 2 3]
Row 1: [2 4 6]
Row 2: [1 3 8]
Row 3: [4 5 6]


## dot product, determinant, inverse, sum, transpose
- We use the **dot function to compute inner products of vectors, to multiply a vector by a matrix, and to multiply matrices**.
- dot is available both as a function in the numpy module and as an instance method of array objects:

In [26]:

x = np.array([[1,2],
              [3,4]]
)
y = np.array([[5,6],
              [7,8]]
)

v = np.array([9,10])
w = np.array([11, 12])

# Inner product of vectors; both produce 219
print(v.dot(w))
print(np.dot(v, w))

# Matrix / vector product; both produce the rank 1 array [29 67]
print(x.dot(v))
print(np.dot(x, v))

# Matrix / matrix product; both produce the rank 2 array
# [[19 22]
#  [43 50]]
print(x.dot(y))
print(np.dot(x, y))

219
219
[29 67]
[29 67]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [42]:
A = np.array([[1, 4], 
              [2, 3]])

det_A = np.linalg.det(A)
print("Determinant of 2x2 matrix A:", round(det_A, 3))


A = np.array([[2, 1, 0],
              [0, 1, -1],
              [0, 2, 4]])
det_A = np.linalg.det(A)
print("Determinant of 3x3 matrix A:", round(det_A, 3))


Determinant of 2x2 matrix A: -5.0
Determinant of 3x3 matrix A: 12.0


In [44]:
# Inverse of a Matrix
from numpy.linalg import inv

A = np.array([[1, 4], 
              [2, 3]])
inverse_matrix = inv(A)
print("Inverse of Matrix:\n", inverse_matrix)


A = np.array([[2, 1, 0],
              [0, 1, -1],
              [0, 2, 4]])
inverse_matrix = inv(A)
print("Inverse of Matrix:\n", inverse_matrix)


Inverse of Matrix:
 [[-0.6  0.8]
 [ 0.4 -0.2]]
Inverse of Matrix:
 [[ 0.5   -0.333 -0.083]
 [ 0.     0.667  0.167]
 [-0.    -0.333  0.167]]


In [28]:
# SUM
x = np.array([[1,2],
              [3,4]]
)

print(np.sum(x))  # Compute sum of all elements; prints "10"
print(np.sum(x, axis=0))  # Compute sum of each column; prints "[4 6]"
print(np.sum(x, axis=1))  # Compute sum of each row; prints "[3 7]"

10
[4 6]
[3 7]


Apart from computing mathematical functions using arrays, we frequently need to reshape or otherwise manipulate data in arrays. The simplest example of this type of operation is **transposing a matrix**; to transpose a matrix, simply use the T attribute of an array object:

In [29]:
# Transpose
x = np.array([[1,2],
              [3,4]]
)
print(x)    # Prints "[[1 2]
            #          [3 4]]"
print(x.T)  # Prints "[[1 3]
            #          [2 4]]"

x = np.array([[1,2],
              [3,4],
              [5,6]]
)
print(x)    
print(x.T)  # out-> [[1 3 5]
            #        [2 4 6]]
            

# Note that taking the transpose of a rank 1 array does nothing:
v = np.array([1,2,3])
print(v)    # Prints "[1 2 3]"
print(v.T)  # Prints "[1 2 3]"

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]
[[1 2]
 [3 4]
 [5 6]]
[[1 3 5]
 [2 4 6]]
[1 2 3]
[1 2 3]


## eigen values and eigen vectors

In [30]:
# How to calculate eigen values/ eigen vestors and also verify for 2X2 matrix
# TAKEN from Lang

# Define a 2x2 matrix
A = np.array([[1, 4], 
              [2, 3]])

eigenvalues, eigenvectors = np.linalg.eig(A)

print(f"Matrix A:\n{A}")
print(f"\nEigenvalues:{eigenvalues}")
print(f"\nEigenvectors (columns):\n{eigenvectors}\n\n")

print(f"Eigen value: {eigenvalues[0]} and its corresponding eigen vector: {eigenvectors[:, 0]}")
print(f"Eigen value: {eigenvalues[1]} and its corresponding eigen vector: {eigenvectors[:, 1]}")

##################################

# First eigenvalue and eigenvector
lambda1 = eigenvalues[0]
v1 = eigenvectors[:, 0]

Av1 = A @ v1
lambda1_v1 = lambda1 * v1

print("\nVerifying First Eigenpair:")
print("A @ v1 =", Av1)
print("λ1 * v1 =", lambda1_v1)
print("Match? ->", np.allclose(Av1, lambda1_v1)) # Returns True if two arrays are element-wise equal within a tolerance.
####################################

# Second eigenvalue and eigenvector
lambda2 = eigenvalues[1]
v2 = eigenvectors[:, 1]

Av2 = A @ v2
lambda2_v2 = lambda2 * v2

print("\nVerifying Second Eigenpair:")
print("A @ v2 =", Av2)
print("λ2 * v2 =", lambda2_v2)
print("Match? ->", np.allclose(Av2, lambda2_v2))


Matrix A:
[[1 4]
 [2 3]]

Eigenvalues:[-1.  5.]

Eigenvectors (columns):
[[-0.894 -0.707]
 [ 0.447 -0.707]]


Eigen value: -1.0 and its corresponding eigen vector: [-0.894  0.447]
Eigen value: 5.0 and its corresponding eigen vector: [-0.707 -0.707]

Verifying First Eigenpair:
A @ v1 = [ 0.894 -0.447]
λ1 * v1 = [ 0.894 -0.447]
Match? -> True

Verifying Second Eigenpair:
A @ v2 = [-3.536 -3.536]
λ2 * v2 = [-3.536 -3.536]
Match? -> True


In [31]:
# How to calculate eigen values/ eigen vestors and also verify for 3X3 matrix
# Taken from Lang

# # Set print precision
# np.set_printoptions(precision=3, suppress=True)

# Define a 3x3 matrix
A = np.array([[2, 1, 0],
              [0, 1, -1],
              [0, 2, 4]])

eigenvalues, eigenvectors = np.linalg.eig(A)

print(f"Matrix A:\n{A}")
print(f"\nEigenvalues:\n{np.round(eigenvalues, 3)}")
print(f"\nEigenvectors (columns):\n{np.round(eigenvectors, 3)}\n\n")

print(f"Eigen value: {eigenvalues[0]} and its corresponding eigen vector: {eigenvectors[:, 0]}")
print(f"Eigen value: {eigenvalues[1]} and its corresponding eigen vector: {eigenvectors[:, 1]}")
print(f"Eigen value: {eigenvalues[2]} and its corresponding eigen vector: {eigenvectors[:, 2]}")

##################################

# First eigenpair
lambda1 = eigenvalues[0]
v1 = eigenvectors[:, 0]

Av1 = A @ v1
lambda1_v1 = lambda1 * v1

print("\nVerifying First Eigenpair:")
print("A @ v1 =", np.round(Av1, 3))
print("λ1 * v1 =", np.round(lambda1_v1, 3))
print("Match? ->", np.allclose(Av1, lambda1_v1))

##################################

# Second eigenpair
lambda2 = eigenvalues[1]
v2 = eigenvectors[:, 1]

Av2 = A @ v2
lambda2_v2 = lambda2 * v2

print("\nVerifying Second Eigenpair:")
print("A @ v2 =", np.round(Av2, 3))
print("λ2 * v2 =", np.round(lambda2_v2, 3))
print("Match? ->", np.allclose(Av2, lambda2_v2))

##################################

# Third eigenpair
lambda3 = eigenvalues[2]
v3 = eigenvectors[:, 2]

Av3 = A @ v3
lambda3_v3 = lambda3 * v3

print("\nVerifying Third Eigenpair:")
print("A @ v3 =", np.round(Av3, 3))
print("λ3 * v3 =", np.round(lambda3_v3, 3))
print("Match? ->", np.allclose(Av3, lambda3_v3))


Matrix A:
[[ 2  1  0]
 [ 0  1 -1]
 [ 0  2  4]]

Eigenvalues:
[2. 2. 3.]

Eigenvectors (columns):
[[ 1.     1.     0.408]
 [ 0.    -0.     0.408]
 [ 0.     0.    -0.816]]


Eigen value: 2.0 and its corresponding eigen vector: [1. 0. 0.]
Eigen value: 2.0 and its corresponding eigen vector: [ 1. -0.  0.]
Eigen value: 3.0 and its corresponding eigen vector: [ 0.408  0.408 -0.816]

Verifying First Eigenpair:
A @ v1 = [2. 0. 0.]
λ1 * v1 = [2. 0. 0.]
Match? -> True

Verifying Second Eigenpair:
A @ v2 = [ 2. -0.  0.]
λ2 * v2 = [ 2. -0.  0.]
Match? -> True

Verifying Third Eigenpair:
A @ v3 = [ 1.225  1.225 -2.449]
λ3 * v3 = [ 1.225  1.225 -2.449]
Match? -> True


## stat related methods

In [32]:
# some stats operations
from scipy import stats

# Create a sample NumPy array
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Calculate statistics
mean_value = np.mean(data)
std_deviation = np.std(data)
variance = np.var(data)
median_value = np.median(data)
min_value = np.min(data)
max_value = np.max(data)
percentile_25 = np.percentile(data, 25)
percentile_75 = np.percentile(data, 75)
# summary = stats.describe(data)

# Print results
print("Mean:", mean_value)
print("Standard Deviation:", std_deviation)
print("Variance:", variance)
print("Median:", median_value)
print("Minimum:", min_value)
print("Maximum:", max_value)
print("25th Percentile:", percentile_25)
print("75th Percentile:", percentile_75)
# print("Summary Statistics:", summary)

Mean: 5.5
Standard Deviation: 2.8722813232690143
Variance: 8.25
Median: 5.5
Minimum: 1
Maximum: 10
25th Percentile: 3.25
75th Percentile: 7.75


In [33]:
# how to calculate mode
arr = np.array([1, 2, 2, 3, 4, 4, 4, 5])

mode_result = stats.mode(arr, keepdims=True)
print("Mode:", mode_result.mode[0])
print("Count:", mode_result.count[0])

Mode: 4
Count: 3


In [34]:
# Create a 3x4 NumPy array
array_2d = np.array([[10, 20, 30, 40],
                     [50, 60, 70, 80],
                     [90, 100, 110, 120]])

print("Original Array:")
print(array_2d)

# Calculate mean, standard deviation, and variance for each column (axis=0)
mean_columns = np.mean(array_2d, axis=0)
std_columns = np.std(array_2d, axis=0)
var_columns = np.var(array_2d, axis=0)

print("\nMean of each column:")
print(mean_columns)

print("\nStandard Deviation of each column:")
print(std_columns)

print("\nVariance of each column:")
print(var_columns)

# Calculate mean, standard deviation, and variance for each row (axis=1)
mean_rows = np.mean(array_2d, axis=1)
std_rows = np.std(array_2d, axis=1)
var_rows = np.var(array_2d, axis=1)

print("\nMean of each row:")
print(mean_rows)

print("\nStandard Deviation of each row:")
print(std_rows)

print("\nVariance of each row:")
print(var_rows)

Original Array:
[[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]]

Mean of each column:
[50. 60. 70. 80.]

Standard Deviation of each column:
[32.66 32.66 32.66 32.66]

Variance of each column:
[1066.667 1066.667 1066.667 1066.667]

Mean of each row:
[ 25.  65. 105.]

Standard Deviation of each row:
[11.18 11.18 11.18]

Variance of each row:
[125. 125. 125.]


In [35]:
# Create a 3x4 NumPy array
array_2d = np.array([[10, 20, 30, 40],
                     [50, 60, 70, 80],
                     [90, 100, 110, 120]])

print("Original Array:")
print(array_2d)

# Calculate sum for each column (axis=0)
sum_columns = np.sum(array_2d, axis=0)
print("\nSum of each column:")
print(sum_columns)

# Calculate minimum for each column (axis=0)
min_columns = np.min(array_2d, axis=0)
print("\nMinimum of each column:")
print(min_columns)

# Calculate maximum for each column (axis=0)
max_columns = np.max(array_2d, axis=0)
print("\nMaximum of each column:")
print(max_columns)

# Calculate median for each column (axis=0)
median_columns = np.median(array_2d, axis=0)
print("\nMedian of each column:")
print(median_columns)

# Calculate sum for each row (axis=1)
sum_rows = np.sum(array_2d, axis=1)
print("\nSum of each row:")
print(sum_rows)

# Calculate minimum for each row (axis=1)
min_rows = np.min(array_2d, axis=1)
print("\nMinimum of each row:")
print(min_rows)

# Calculate maximum for each row (axis=1)
max_rows = np.max(array_2d, axis=1)
print("\nMaximum of each row:")
print(max_rows)

# Calculate median for each row (axis=1)
median_rows = np.median(array_2d, axis=1)
print("\nMedian of each row:")
print(median_rows)

Original Array:
[[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]]

Sum of each column:
[150 180 210 240]

Minimum of each column:
[10 20 30 40]

Maximum of each column:
[ 90 100 110 120]

Median of each column:
[50. 60. 70. 80.]

Sum of each row:
[100 260 420]

Minimum of each row:
[10 50 90]

Maximum of each row:
[ 40  80 120]

Median of each row:
[ 25.  65. 105.]


In [36]:
# optional
import numpy as np

x = np.array([10, 20, 30, 40, 50])
y = np.array([5,  10, 15, 20, 25])

corr_matrix = np.corrcoef(x, y)
print(corr_matrix)


cov_matrix = np.cov(x, y)
print(cov_matrix)

[[1. 1.]
 [1. 1.]]
[[250.  125. ]
 [125.   62.5]]


## miscellaneous
- isin
- where
- set operations

In [37]:
# isin(): inbuilt method. Checks whether each element in the input array is present in a list of values.
# It does Membership Testing

# Check if elements are in a list or array
a = np.array([1, 2, 3, 4, 5])
b = np.array([2, 4, 6])

result = np.isin(a, b) # Returns a boolean array showing whether each element of the first array exists in the second array.
print(result)         # Output: [False  True False  True False]

# To get actual matching values:
print(a[result])      # Output: [2 4]


[False  True False  True False]
[2 4]


### where()
The np.where() function in NumPy allows you to find the indices of elements in an array that satisfy acertain condition. It can also be used to create new arrays based on conditions

Returns indices (or applies logic) where a condition is True.

You can also use: 

np.where(condition, x, y)  → Returns x if condition is True, else y.

In [38]:
# where()

# Create a sample NumPy array
array = np.array([10, 20, 30, 40, 50, 60])

# Find indices where the elements are greater than 30
indices = np.where(array > 30) # returns a 2-tuple
print(f"Indices: {indices}, type: {type(indices)}")
print(f"Indices of elements greater than 30: {indices[0]}")  # Output the indices
print("*****************************")

# Create a new array based on a condition
new_array = np.where(array > 30, 'Greater than 30', '30 or less')
print("New Array based on condition:")
print(new_array)
print("^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^")

# Create a 2D NumPy array
array_2d = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]])

# Find indices where the elements are greater than 5
indices_2d = np.where(array_2d > 5)
print("Indices of elements greater than 5 in 2D array:", indices_2d)

# Create a new array based on a condition
new_array_2d = np.where(array_2d > 5, 'Greater than 5', '5 or less')
print("\nNew 2D Array based on condition:")
print(new_array_2d)

Indices: (array([3, 4, 5], dtype=int64),), type: <class 'tuple'>
Indices of elements greater than 30: [3 4 5]
*****************************
New Array based on condition:
['30 or less' '30 or less' '30 or less' 'Greater than 30'
 'Greater than 30' 'Greater than 30']
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Indices of elements greater than 5 in 2D array: (array([1, 2, 2, 2], dtype=int64), array([2, 0, 1, 2], dtype=int64))

New 2D Array based on condition:
[['5 or less' '5 or less' '5 or less']
 ['5 or less' '5 or less' 'Greater than 5']
 ['Greater than 5' 'Greater than 5' 'Greater than 5']]


In [39]:
# set operations

a = np.array([1, 2, 3, 4])
b = np.array([3, 4, 5, 6])

print(np.intersect1d(a, b))  # Output: [3 4]  Elements common to both arrays
print(np.setdiff1d(a, b))  # Output: [1 2]  Elements in a that are not in b
print(np.union1d(a, b))  # Output: [1 2 3 4 5 6] All unique elements from both arrays

# and there are many others

[3 4]
[1 2]
[1 2 3 4 5 6]


In [40]:
## others clip, swapaxes, delete, put