### Topics
- array indexing / slicing: It is a way to access elements

## Access and Modify elements

In [4]:
import numpy as np

In [5]:
# accessing elements and modifing element
# NOTE: indexing starts with 0

# 1.  Lets access 1D array of shape (4) and modify an element
a = np.array([60, 43, 12, 35])   # Create a rank 1(i.e. 1D) array

print(a[0])
print(a[2])

# Change an element of the array
a[0] = 5
print(a)
print("####################")

60
12
[ 5 43 12 35]
####################


In [6]:
# 2. access 2D array and modify elements
# Use: b[row_index][column_index]
# or   b[row_index, column_index]

# Create a 2D array of shape 2X3
b = np.array([[1,2,3],
              [4,5,6]]
)    

print(b[0][0]) # row=0, col=0
print(b[0, 0])

print(b[0][1]) # row_idx=0, col_idx=1
print(b[0, 1])

print(b[1][2]) # row_idx=1, col_idx=2
print(b[1, 2])


# lets change an element. There are 2 ways
# b[0][2] = 9
b[0,2]  = 9 
print(b)

1
1
2
2
6
6
[[1 2 9]
 [4 5 6]]


In [13]:
# ADVANCED: 3. access 3D array and modify elements
# Use: b[block_index][row_index][column_index]
# or   b[block_index, row_index, column_index]

# lets create a 3D array of shape 2X3X5
b = np.array([
    [  # First block (depth index 0)
        [1, 2, 3, 4, 5],      # row=0
        [6, 7, 8, 9, 10],     # row=1
        [11, 12, 13, 14, 15]  # row=2
    ],
    
    [  # Second block (depth index 1)
        [16, 17, 18, 19, 20], # row=0
        [21, 22, 23, 24, 25], # row=1
        [26, 27, 28, 29, 30]  # row=2
    ]
])

print(b[0][2][0])  # depth_idx=0, row_idx=2, col_idx=0
print(b[0, 2, 0])  # depth_idx=0, row_idx=2, col_idx=0 

print(b[1, 2, 0])  # depth_idx=1, row_idx=2, col_idx=0
print(b[1, 0, 3])  # depth_idx=1, row_idx=0, col_idx=3


3
(2, 3, 5)
11
11
26
19


## Array slicing

**Slicing**: Similar to Python lists, numpy arrays can be sliced. 
- Since arrays may be multidimensional, you must **specify a slice for each dimension of the array**:

In [19]:
np.random.seed(42) # Set the seed for reproducibility

# Lets create a 4X8 array with random numbers between 0 to 10
a = np.random.randint(0, 10, size=(4, 8))
print(a)


# I want a subarray consisting of the first 2 rows(i.e. rows 0 and 1)
# and columns 1 and 2. I use slicing
b = a[0:2, 1:3]
print(b)
print("##########################")

# I want a subarray consisting of row_idx from 1 to 3 and
# and column_idx from 3 to  and 7. I use slicing
b = a[1:4, 3:8]
print(b)
print("##########################")


# A slice of an array is a view into the same data, so modifying it
# will modify the original array.
print("Before:\n", a)   
b[0, 0] = -9     # b[0, 0] is the same piece of data as a[1, 3]
print("After:\n", a)

[[6 3 7 4 6 9 2 6]
 [7 4 3 7 7 2 5 4]
 [1 7 5 1 4 0 9 5]
 [8 0 9 2 6 3 8 2]]
[[3 7]
 [4 3]]
##########################
[[7 7 2 5 4]
 [1 4 0 9 5]
 [2 6 3 8 2]]
##########################
Before:
 [[6 3 7 4 6 9 2 6]
 [7 4 3 7 7 2 5 4]
 [1 7 5 1 4 0 9 5]
 [8 0 9 2 6 3 8 2]]
After:
 [[ 6  3  7  4  6  9  2  6]
 [ 7  4  3 -9  7  2  5  4]
 [ 1  7  5  1  4  0  9  5]
 [ 8  0  9  2  6  3  8  2]]


# STOP

In [9]:
# SKIP (OPTIONAL) You can also mix integer indexing with slice indexing. However, doing
# so will yield an array of lower rank than the original array.

# Create the following rank 2 array with shape (3, 4)
a = np.array([[1,2,3,4],
              [5,6,7,8],
              [9,10,11,12]]
)

# Two ways of accessing the data in the middle row of the array.
# Mixing integer indexing with slices yields an array of lower rank,
# while using only slices yields an array of the same rank as the original array:
row_r1 = a[1, :]    # Rank 1 view of the second row of a
row_r2 = a[1:2, :]  # Rank 2 view of the second row of a
print(row_r1, row_r1.shape)  # Prints "[5 6 7 8] (4,)"
print(row_r2, row_r2.shape)  # Prints "[[5 6 7 8]] (1, 4)"

# We can make the same distinction when accessing columns of an array:
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print(col_r1, col_r1.shape)  # Prints "[ 2  6 10] (3,)"
print(col_r2, col_r2.shape)  # Prints "[[ 2]
                             #          [ 6]
                             #          [10]] (3, 1)"

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)


Integer array indexing:
- When you index into numpy arrays using slicing, the resulting array view will always be a subarray of the original array.
- In contrast, integer array indexing allows you to construct arbitrary arrays using the data from another array.
Here is an example:

In [10]:
# (SKIP) One useful trick with integer array indexing is selecting or mutating one element from each row of a matrix:

# Create a new array from which we will select elements
a = np.array([[1,2,3],
              [4,5,6],
              [7,8,9],
              [10, 11, 12]]
)

print(f"a: \n{a}")

# Create an array of col_indices: 0, 2, 0, 1
col_indices = np.array([0, 2, 0, 1])

# Select one element from each row of a using the indices in col_indices
print(a[np.arange(4), col_indices])  # Prints "[ 1  6  7 11]"

# Mutate one element from each row of a using the indices in col_indices
a[np.arange(4), col_indices] += 10

print(a)  # prints "array([[11,  2,  3],
          #                [ 4,  5, 16],
          #                [17,  8,  9],
          #                [10, 21, 12]])

a: 
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[ 1  6  7 11]
[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]
