## Linear Algebra

## Topics
- Matrix Addition, Subtraction, Multiplication


In [1]:
import numpy as np

### Matrix addition and subtraction
- Both matrix should have same shape
- Perform element-wise addition / subtraction


#### e.g. Addition
```
A = [[1, 2, 3],
     [4, 5, 6]]
A is 2×3

B = [[5, 7, 9],
     [2, 3, 8]]
B is 2×3

A + B 
= [ (1+5)   (2+7)   (3+9)
    (4+2)   (5+3)   (6+8)
  ]

= [   6       9      12
      6       8      14
  ] 

```

In [2]:
# Addition: A is 2x3 matrix, and B is 2X3 matrix

A = np.array([[1, 2, 3],
              [4, 5, 6]]
) 

B = np.array([[5, 7, 9],
              [2, 3, 8]]
) 

result = A + B
print(result)

[[ 6  9 12]
 [ 6  8 14]]



#### e.g. Subtraction
```
A = [[1, 2, 3],
     [4, 5, 6]]
A is 2×3

B = [[5, 7, 9],
     [2, 3, 8]]
B is 2×3

A - B 
= [ (1-5)   (2-7)   (3-9)
    (4-2)   (5-3)   (6-8)
  ]

= [   -4      -5     -6
       2       2     -2
  ] 

```

In [3]:
# Subtraction: A is 2x3 matrix, and B is 2X3 matrix

A = np.array([[1, 2, 3],
              [4, 5, 6]]
) 

B = np.array([[5, 7, 9],
              [2, 3, 8]]
) 

result = A - B
print(result)

[[-4 -5 -6]
 [ 2  2 -2]]


### Matrix multiplication and dot product
- Matrix multiplication requires that the **number of columns in the first matrix must match the number of rows in the second matrix**
- If A is **n X m** matrix and B is **m X p** matrix, then matrix multiplication **A*B** gives **n X p** matrix

e.g.1
```
A = [[1, 2, 3],
     [4, 5, 6]]
A is 2×3

B = [[7, 8],
     [9, 10],
     [11, 12]]
B is 3×2

A @ B 
= [ (1×7+2×9+3×11)   (1×8+2×10+3×12)
    (4×7+5×9+6×11)   (4×8+5×10+6×12)
  ]
= [ 58   64
    139  154
  ] 

```

e.g.2:
```
A = [[1, 2],
     [3, 4],
     [5, 6]]
 3x2 matrix

B = [[7, 8, 9],
     [10, 11, 12]]
 2x3 matrix

A @ B
= [ 
    (1×7+2×10)   (1×8+2×11)   (1×9+2×12)
    (3×7+4×10)   (3×8+4×11)   (3×9+4×12) 
    (5×7+6×10)   (5×8+6×11)   (5×9+6×12)
 ]

= [[ 27  30  33]
   [ 61  68  75]
   [ 95 106 117]]
```

e.g.3:
```
A = [[1, 2],
     [3, 4],
     [5, 6]]
 3x2 matrix

B = [[7,  8,  9,  3, 1],
     [10, 11, 12, 2, 1]]
2x5 matrix

A @ B is a 3X5 matrix
A @ B =
    [[ 27  30  33   7   3]
     [ 61  68  75  17   7]
     [ 95 106 117  27  11]]

```

In [10]:
# Multiplication e.g.1: A is 2x3 matrix, and B is 3X2 matrix. The product would be 2X2 matrix

A = np.array([[1, 2, 3],
              [4, 5, 6]])  # 2x3 matrix

B = np.array([[7, 8],
              [9, 10],
              [11, 12]])    # 3x2 matrix

# 3 ways to perform Matrix multiplication 
result = A @ B 
# result = np.matmul(A, B) 
# result = np.dot(A, B) # not a good way
# result = B @ A # Order of dot product  matters

print("Matrix multiplication:\n", result)

Matrix multiplication:
 [[ 58  64]
 [139 154]]


In [5]:
# Multiplication e.g.2: A is 3x2 matrix, and B is 2X3 matrix. The product would be 3X3 matrix

A = np.array([[1, 2],
              [3, 4],
              [5, 6]])  # 3x2 matrix

B = np.array([[7, 8, 9],
              [10, 11, 12]])  # 2x3 matrix

# 3 ways to perform Matrix multiplication 
result = A @ B 
# result = np.matmul(A, B) 
# result = np.dot(A, B) # not a good way

print("Matrix multiplication:\n", result)

Matrix multiplication:
 [[ 27  30  33]
 [ 61  68  75]
 [ 95 106 117]]


In [6]:
# Multiplication e.g.3: A is 3x2 matrix, and B is 2X5 matrix. The product would be 3X5 matrix

A = np.array([[1, 2],
              [3, 4],
              [5, 6]])  # 3x2 matrix

B = np.array([[7,  8,  9,  3, 1],
              [10, 11, 12, 2, 1]]
            
            )  # 2x5 matrix

# 3 ways to perform Matrix multiplication 
result = A @ B 
# result = np.matmul(A, B) 
# result = np.dot(A, B) # not a good way

print("Matrix multiplication:\n", result)

Matrix multiplication:
 [[ 27  30  33   7   3]
 [ 61  68  75  17   7]
 [ 95 106 117  27  11]]


####  dot product of vectors
- We use the **dot function  (a) to compute inner products of 2 vectors, (b) to multiply a vector by a matrix, and (c) to multiply matrices**.
- dot is available both as a function in the numpy module and as an instance method of array objects

In [7]:
# Here we perform dot product between two vectors

v = np.array([7,    8,    9]) # Candidate's scores on 3 subjects
w = np.array([0.1, 0.8, 0.1]) # Weights for each subject

# Inner product of vectors; both produce same result
print(np.dot(v, w)) # Weighted score calculation using dot product
print(v.dot(w))

8.0
8.0


In [8]:
# Dot product between matrix and vector (order matters): A*x
# If A is (m, n) and x is (n,), then np.dot(A, x) would have shape=(m,)

A = np.array([[1, 2],
              [3, 4],
              [5, 6]])   # 3x2 matrix
x = np.array([7, 8])     # 2-dimensional vector

result = np.dot(A, x)    # shape: (3,)
print(result)  

[23 53 83]
