# Export and Import Data to CSV (Comma Seperated Value) file

### Export data to CSV

In [22]:
import numpy as np

In [23]:
# create 2D data of shape 12X10 

arr = np.random.randint(1, 10, size=(12,10))
print(arr)

[[4 8 9 2 9 8 8 3 9 6]
 [7 9 4 1 4 6 8 4 2 4]
 [8 1 3 2 7 4 8 8 8 2]
 [9 5 1 1 8 9 8 4 1 2]
 [3 4 9 7 4 9 6 8 2 8]
 [3 2 4 1 2 3 2 9 2 1]
 [6 5 5 5 1 4 1 9 5 2]
 [6 2 5 9 4 9 7 9 6 4]
 [9 4 9 6 4 8 7 3 7 5]
 [4 8 7 4 2 4 6 6 7 5]
 [6 7 4 5 8 7 5 2 6 6]
 [6 6 9 2 2 3 7 3 3 7]]


In [24]:
# Export the arr to CSV file with comma delimiter

np.savetxt("data_raw.csv", arr, delimiter=",")

### Import data from CSV file

In [25]:
# Now lets import the above data from CSV file that we just created

data = np.genfromtxt("data_raw.csv", delimiter=",")
print(data)
print(data.dtype)

[[4. 8. 9. 2. 9. 8. 8. 3. 9. 6.]
 [7. 9. 4. 1. 4. 6. 8. 4. 2. 4.]
 [8. 1. 3. 2. 7. 4. 8. 8. 8. 2.]
 [9. 5. 1. 1. 8. 9. 8. 4. 1. 2.]
 [3. 4. 9. 7. 4. 9. 6. 8. 2. 8.]
 [3. 2. 4. 1. 2. 3. 2. 9. 2. 1.]
 [6. 5. 5. 5. 1. 4. 1. 9. 5. 2.]
 [6. 2. 5. 9. 4. 9. 7. 9. 6. 4.]
 [9. 4. 9. 6. 4. 8. 7. 3. 7. 5.]
 [4. 8. 7. 4. 2. 4. 6. 6. 7. 5.]
 [6. 7. 4. 5. 8. 7. 5. 2. 6. 6.]
 [6. 6. 9. 2. 2. 3. 7. 3. 3. 7.]]
float64


In [26]:
# OPTIONAL: Lets convert the above to dtype=np.uint8

data = data.astype(np.uint8)
print(data)
print(data.dtype)

[[4 8 9 2 9 8 8 3 9 6]
 [7 9 4 1 4 6 8 4 2 4]
 [8 1 3 2 7 4 8 8 8 2]
 [9 5 1 1 8 9 8 4 1 2]
 [3 4 9 7 4 9 6 8 2 8]
 [3 2 4 1 2 3 2 9 2 1]
 [6 5 5 5 1 4 1 9 5 2]
 [6 2 5 9 4 9 7 9 6 4]
 [9 4 9 6 4 8 7 3 7 5]
 [4 8 7 4 2 4 6 6 7 5]
 [6 7 4 5 8 7 5 2 6 6]
 [6 6 9 2 2 3 7 3 3 7]]
uint8
