# Changing the shape of numpy arrays: Transpose
- transpose

In [19]:
import numpy as np

## Transpose
- For 2D arrays (matrices), it swaps rows and columns.
- For n-dimensional arrays, it reorders the dimensions based on the given axes.

### Note
- You can use **array.T** This is best for 2D array.
- Or you can transpose using **np.transpose(array, axes=None)**. This can  be used for higher dimensions.


### Application:
- Preparing data for algorithms like matrix multiplication or PCA (Principal Component Analysis), which require certain shape conventions.

In [20]:
# Transpose for 2D using array.T: nXm matrix becomes mXn matrix 

# Using x.T. It is best for 2D and commonly used in 2D
# e.g.1: If shape of x is 2X3, then shape of x.T becomes 3X2
x = np.array([
    [5, 3, 7], 
    [2, 5 ,9]] 
)
print(x, "\n")

transpose = x.T
print(transpose)  

[[5 3 7]
 [2 5 9]]
[[5 2]
 [3 5]
 [7 9]]


In [21]:
# e.g.2: If shape of x is 3X4. Then shape of x.T is 4X3
x = np.array([[6, 2, 3, 4],
              [3, 4, 5, 6],
              [7, 8, 5, 9]]
)
print(x, "\n")

transpose = x.T
print(transpose)  

[[6 2 3 4]
 [3 4 5 6]
 [7 8 5 9]]
[[6 3 7]
 [2 4 8]
 [3 5 5]
 [4 6 9]]


In [22]:
# e.g.3: Note that taking the transpose of a rank 1 array does nothing:
v = np.array([1,2,3])
print(v)    
print(v.T)  

[1 2 3]
[1 2 3]


In [23]:
# Transpose for 2D using np.transpose(): nXm matrix becomes mXn matrix 

# e.g.1: If shape of x is 2X3. Then shape of np.transpose(x) is 3X2
x = np.array([[1, 2, 3], 
              [4, 5 ,6]] 
)
print(x)

transpose = np.transpose(x)
print(transpose)  

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


In [24]:
# e.g.2: If shape of x is 3X4. Then shape of np.transpose(x) is 4X3
x = np.array([[6, 2, 3, 4],
              [3, 4, 5, 6],
              [7, 8, 5, 9]]
)
print(x)

transpose = np.transpose(x)
print(transpose)

[[6 2 3 4]
 [3 4 5 6]
 [7 8 5 9]]
[[6 3 7]
 [2 4 8]
 [3 5 5]
 [4 6 9]]


# STOP

In [27]:
# ADVANCED: transpose of 3D and higher

# Create a 3D array of shape 2X3X4
a = np.arange(24).reshape(2, 3, 4) 
print("a:\n", a)
print(a.shape)  # (2, 3, 4)

# Default transpose: reverses axes order
b = np.transpose(a)
print("b:\n", b)
print(b.shape)  # (4, 3, 2)

a:
 [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
(2, 3, 4)
b:
 [[[ 0 12]
  [ 4 16]
  [ 8 20]]

 [[ 1 13]
  [ 5 17]
  [ 9 21]]

 [[ 2 14]
  [ 6 18]
  [10 22]]

 [[ 3 15]
  [ 7 19]
  [11 23]]]
(4, 3, 2)


In [28]:
# ADVANCED: transpose of 3D and higher

# Create a 3D array of shape 2X3X4
a = np.arange(24).reshape(2, 3, 4) 
print("a:\n", a)
print(a.shape)  # (2, 3, 4)

# Custom axis order: I want axes ordered as 1, 0, 2
c = np.transpose(a, axes=(1, 0, 2))
print("c:\n", c)
print(c.shape)  # (3, 2, 4)

a:
 [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
(2, 3, 4)
c:
 [[[ 0  1  2  3]
  [12 13 14 15]]

 [[ 4  5  6  7]
  [16 17 18 19]]

 [[ 8  9 10 11]
  [20 21 22 23]]]
(3, 2, 4)
