# Broadcasting
Broadcasting in NumPy is a set of rules that allow array operations (like addition, multiplication, etc.) **between arrays of different shapes without making explicit copies of data**.

Instead of looping manually, NumPy automatically "stretches" the smaller array across the larger one without really copying values, making operations efficient.


## Broadcasting Rules

When performing element-wise operations between two arrays:

Compare shapes from right to left.

Two dimensions are compatible when:
- They are equal, OR
- One of them is 1.

***If dimensions don’t match and neither is 1, NumPy throws an error.***

***If compatible, NumPy "broadcasts" (virtually repeats) the smaller array.***


## Why Broadcasting is Useful ?
- Eliminates explicit loops (for)
- Saves memory (no real replication)
- Much faster (uses vectorized C operations under the hood)

In [1]:
import numpy as np

In [2]:
# Example 1: Vector + Scalar

a = np.array([1, 2, 3, 4])
b = 3

res = a + b
print(res)

[4 5 6 7]


### The scalar 3 is broadcast to [3, 3, 3, 3].

In [3]:
# Example 2: Matrix + Vector

a = np.array([[1, 2, 3],
              [4, 5, 6]]
) # 2x3 matrix

b = np.array([10, 20, 30]) # 1X3 matrix

res = a + b
print(res)

[[11 22 33]
 [14 25 36]]


### b is broadcast across each row.

In [4]:
# Example 3: Different Dimensions

a = np.array([[1],
              [2],
              [3]]
)   # shape (3,1)
b = np.array([10, 20, 30])      # shape (3,)

res = a + b
print(res)

(3,)
[[11 21 31]
 [12 22 32]
 [13 23 33]]


a.shape = (3,1)

b.shape = (3,) -> (1,3)

Resulting shape = (3,3)


Suppose you want to add:

Shape (4,1,3)

Shape ( 5,1)

Steps:

1) Pad shapes for alignment:
- (4,1,3)
- (1,5,1)

2) Compare:
- 3 vs 1 -> OK
- 1 vs 5 -> OK
- 4 vs 1 -> OK

3) Result shape: (4,5,3)

In [6]:
# Example of above

# Shape (4,1,3)
a = np.arange(12).reshape(4,1,3)

# Shape (5,1)
b = np.arange(5).reshape(5,1)

print("Shape of a:", a.shape)
print("Shape of b:", b.shape)

res = a + b
print("Shape of result:", res.shape)
print(res)


Shape of a: (4, 1, 3)
Shape of b: (5, 1)
Shape of result: (4, 5, 3)
[[[ 0  1  2]
  [ 1  2  3]
  [ 2  3  4]
  [ 3  4  5]
  [ 4  5  6]]

 [[ 3  4  5]
  [ 4  5  6]
  [ 5  6  7]
  [ 6  7  8]
  [ 7  8  9]]

 [[ 6  7  8]
  [ 7  8  9]
  [ 8  9 10]
  [ 9 10 11]
  [10 11 12]]

 [[ 9 10 11]
  [10 11 12]
  [11 12 13]
  [12 13 14]
  [13 14 15]]]


In [7]:
# When Broadcasting Fails

# step1: Following fails. ValueError: operands could not be broadcast together
a = np.array([1, 2, 3, 4])
b = np.array([7, 7])

# res = a + b  # ERROR 

In [8]:
# step2: Following works
a = np.array([1, 2, 3, 4])
b = np.array([7])

res = a + b   
print(res)

[ 8  9 10 11]
