# Basic matrix operation using numpy


In [31]:
import numpy as np

In [32]:
# Here x could be an image of size 2X2.

# Elementwise addition (e.g., applying a brightness mask y): Requirement is shapes of x and y should be same
x = np.array([[100, 150],
              [140, 200]]
)

y = np.array([[5, 10],
              [15, 20]]
)

res = x + y
# res = np.add(x, y)
print("Add filter (brightness boost):\n", res)
########################

# Adding a constant (increase brightness uniformly)
x = np.array([[100, 150],
              [140, 200]]
)

res = x + 50
print("Add 50 to all pixels (brightness adjustment):\n", res)
########################

# Element-wise subtraction (e.g., remove background or detect changes from 1 frame to another)
# x could be one frame and y could be another frame
x = np.array([[100, 150],
              [140, 200]]
)

y = np.array([[5, 10],
              [15, 20]]
)

res = x - y
# res = np.subtract(x, y)
print("Subtract filter (change detection):\n", res)

Add filter (brightness boost):
 [[105 160]
 [155 220]]
Add 50 to all pixels (brightness adjustment):
 [[150 200]
 [190 250]]
Subtract filter (change detection):
 [[ 95 140]
 [125 180]]


In [33]:
# Element-wise multiplication (e.g., applying a weight y or blending mask y to image x)

x = np.array([[100, 150],
              [140, 200]]
)

y = np.array([[.5, .10],
              [.15, .20]]
)

res = x * y
# res = np.multiply(x, y)
print("Pixel-wise blending (weighted effect):\n", res)

Pixel-wise blending (weighted effect):
 [[50. 15.]
 [21. 40.]]


In [34]:
# Now lets perform element-wise division
x = np.array([[100, 150],
              [130, 20]]
)

y = np.array([[.5, .10],
              [.15, .20]]
)

res = x / y
# res = np.divide(x, y)
print(res)

[[ 200.         1500.        ]
 [ 866.66666667  100.        ]]
