In [2]:
import numpy as np


---

### 1. **What is NumPy and why is it used?**

**Answer:**
NumPy (Numerical Python) is a Python library used for numerical computing. It provides support for **multi-dimensional arrays**, **mathematical functions**, **linear algebra**, **Fourier transforms**, and more. It’s faster than regular Python lists because it uses **vectorization** and **C-optimized implementations**.

---

### 2. **How do you create a NumPy array?**

**Answer:**

```python
import numpy as np

# From a list
arr = np.array([1, 2, 3, 4])

# Create 2X3 array of zeros
zeros = np.zeros((2, 3))

# Create array of ones
ones = np.ones((3, 3))

# Create array with range
arange = np.arange(0, 10, 2)
```


### How do you check the shape of arrays in numpy ?
print(arr.shape)


---

### 3. **What is the difference between a Python list and a NumPy array?**

**Answer:**

* **Lists** can store different data types, while **NumPy arrays** require elements of the same data type.
* **NumPy arrays** support **vectorized operations** (element-wise), making them much faster than lists.
* NumPy arrays consume less memory compared to lists.

```
l   = [1, "hello", True, 2.45, 3, 8] # contains int, str, Boolean, float
arr = np.array(l)
print(arr.dtype)
```
---


In [ ]:
# different datatypes
l   = [1, "hello", True, 2.45, 3, 8] # contains int, str, Boolean, float
arr = np.array(l)
print(arr.dtype)

In [7]:
# vectorized operation

la = [1, 2, 3]
lb = [4, 5, 6]

# vectorized operation in numpy
a = np.array(la)
b = np.array(lb)

print("a*b:", a*b)

# same calculation in python list:
result = [a*b for a, b in zip(la, lb)]
print("a*b:", result)

result  = []
for i in range(len(la)):
   result.append(la[i]*lb[i])
print("a*b:", result)

a*b: [ 4 10 18]
a*b: [4, 10, 18]
a*b: [4, 10, 18]


In [ ]:

### 4. **How do you check the shape and datatype of a NumPy array?**

**Answer:**

```python
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.shape)   # (2, 3)
print(arr.dtype)   # int64 (depends on system)
```

---

### 5. **How do you reshape an array in NumPy? Say from 1D to 2D**

**Answer:**

```python
arr = np.arange(12)   # [0, 1, 2, ..., 11]
reshaped = arr.reshape(3, 4)  # 3x4 matrix
```

`reshape()` changes the dimensions of an array without changing its data.


In [10]:
# reshape 1D to 2D: Note the number of elements should be same
arr = np.arange(12)   # [0, 1, 2, ..., 11]
reshaped = arr.reshape(3, 4)  # 3x4 matrix
print(arr.shape)
print(reshaped.shape)

(12,)
(3, 4)


In [15]:
# reshape 1D to 3D array: Note the number of elements should be same

arr = np.arange(12)   # [0, 1, 2, ..., 11]
# reshaped = arr.reshape(2, 6, 1)
# reshaped = arr.reshape(2, 3, 2)
reshaped = arr.reshape(3, 4, 1)
# reshaped = arr.reshape(3, 4, 2) # ERROR

print(arr.shape)
print(reshaped.shape)

(12,)
(3, 4, 1)


In [ ]:

---

### 6. **How do you perform element-wise operations on NumPy arrays?**

**Answer:**

```python
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a + b)   # [5, 7, 9]
print(a * b)   # [4, 10, 18]
print(a ** 2)  # [1, 4, 9]
```

NumPy supports **broadcasting** for operations across different shapes.

---

### 7. **How do you compute statistical measures in NumPy (mean, median, std)?**

**Answer:**

```python
arr = np.array([1, 2, 3, 4, 5])

print(np.mean(arr))   # 3.0
print(np.median(arr)) # 3.0
print(np.std(arr))    # 1.4142...
```

---

### 8. **What is broadcasting in NumPy?**

**Answer:**
Broadcasting allows NumPy to perform operations on arrays of different shapes by **automatically expanding dimensions**.
Example:

```
a = np.array([1, 2, 3])
b = 2
print(a * b)   # [2, 4, 6]
```

Here, `b` is broadcasted to match `a`.

---

### 9. **How do you slice and index a NumPy array?**

**Answer:**

```python
arr = np.array([10, 20, 30, 40, 50])

print(arr[1:4])   # [20 30 40]
print(arr[-1])    # 50
print(arr[:3])    # [10 20 30]

matrix = np.array([[1, 2, 3], [4, 5, 6]])
print(matrix[0, 1])   # 2
print(matrix[:, 2])   # [3 6]
```

---

In [16]:
arr = np.array([10, 20, 30, 40, 50])

print(arr[1:4])   # [20 30 40]
print(arr[-1])    # 50
print(arr[:3])    # [10 20 30]

matrix = np.array(
    [[1, 2, 3],
     [4, 5, 6]]
)
print(matrix[0, 1])   # 2
print(matrix[:, 2])   # [3 6]


[20 30 40]
50
[10 20 30]
2
[3 6]


In [ ]:
### 10. **How do you find unique values and their counts in a NumPy array?**

**Answer:**

```python
arr = np.array([10, 20, 20, 30, 30, 40, 30, 40])
unique, counts = np.unique(arr, return_counts=True)

print(unique)  
print(counts)  
```

---

In [19]:
arr = np.array([10, 20, 20, 30, 30, 40, 30, 40])
unique, counts = np.unique(arr, return_counts=True)

print(unique)  
print(counts)  

[10 20 30 40]
[1 2 3 2]
