# Random Number Generation
Here I use python and numpy
- Linear Congruential Generator
- Middle Square Method
- Blum Blum Shub

In [12]:
import numpy as np

Here I show 3 simple function that are used for random number generation.

## 1. Linear Congruential Generator (LCG):
```
𝑋(n+1) = (a * X(n) + c ) mod m

Let a=5, c=3, m=16

and start with seed X(0) = 7

So,

X(1) = (5*7+3) mod16 = (35+3) mod16 = 38 mod16 = 6

X(2) = (5*6+3) mod16 = (30+3) mod16 = 33 mod16 = 1

X(3) = (5*1+3) mod16 = (5+3) mod16 = 8 mod16 = 8

X(4) = 11 and so on

So the random sequence with seed=7 is 7, 6, 1, 8, 11, …
```

In [13]:
# Linear Congruential Generator (LCG)
# step1: Using plain python

def lcg(seed, a=5, c=3, m=16, n=10):
    numbers = [seed]
    x = seed
    for _ in range(n-1):
        x = (a * x + c) % m
        numbers.append(x)
    return numbers


# Call above. Generate 10 random numbers
sequence = lcg(seed=7, n=10)
print(sequence)

# Above is OK for upto 10K random numbers. The speed would go down as numbers increase

[7, 6, 1, 8, 11, 10, 5, 12, 15, 14]


In [14]:
# step2: Using numpy for generating 1 million+ random numbers

def lcg_numpy(seed, a=5, c=3, m=16, n=10):
    numbers = np.empty(n, dtype=np.int64)
    numbers[0] = seed
    for i in range(1, n):
        numbers[i] = (a * numbers[i-1] + c) % m
    return numbers

# Call above. Generate 10 random numbers
sequence = lcg_numpy(7, n=10)
print(sequence)

[ 7  6  1  8 11 10  5 12 15 14]


## 2. Middle Square Method
```
Start with a seed 𝑋(0). Square it. Take the middle digits as the next number. And keep repeating

Example:

Seed = 5735

Square of 5735 = 32890225

Middle 4 digits = 8902

Next seed = 8902 → repeat.
```

In [15]:
# Middle Square Method

def middle_square(seed, n=10, width=4):
    """
    seed  : initial seed (int)
    n     : number of random numbers to generate
    width : number of digits to keep (e.g., 4 → middle 4 digits)
    """
    numbers = np.empty(n, dtype=np.int64)
    x = seed
    for i in range(n):
        numbers[i] = x
        sq = str(x * x).zfill(width * 2)  # ensure enough digits with leading zeros
        mid = len(sq) // 2
        x = int(sq[mid - width//2 : mid + width//2])
    return numbers

sequence = middle_square(seed=5735, n=10, width=4)
print(sequence)


[5735 8902 2456  319 1017  342 1169 3665 4322 6796]


## 3. Blum Blum Shub (BBS)
```
X(n+1) = X(n)² mod M
where M = p*q, with p,q being large prime numbers.

Example (small primes):
p=7, q=11 -> M = 77
Seed X(0) = 5
X(1) = 5² mod77 = 25
X(2) = 25² mod77 = 9
X(3) = 9² mod77 = 4,

Sequence: 5, 25, 9, 4, …
```

In [16]:
# Blum Blum Shub

def bbs(seed, p, q, n=10):
    """
    seed : initial value
    p, q : large primes
    n    : how many numbers to generate
    """
    M = p * q
    numbers = np.empty(n, dtype=np.int64)
    x = seed
    for i in range(n):
        numbers[i] = x
        x = (x * x) % M
    return numbers

sequence = bbs(seed=5, p=7, q=11, n=10)
print(sequence)


[ 5 25  9  4 16 25  9  4 16 25]
