In [1]:
import numpy as np


In [2]:
# Create a 2D array (matrix)
arr2d = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print("2D Array:\n", arr2d)


2D Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
arr2d = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

# Sum of all elements
total_sum = np.sum(arr2d)
print("Total Sum:", total_sum)


Total Sum: 45


In [5]:
arr2d = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

# Sum along rows (axis=1)
row_sum = np.sum(arr2d, axis=1)
print("Sum along rows (axis=1):", row_sum)


Sum along rows (axis=1): [ 6 15 24]


In [6]:
arr2d = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

# Sum along columns (axis=0)
col_sum = np.sum(arr2d, axis=0)
print("Sum along columns (axis=0):", col_sum)


Sum along columns (axis=0): [12 15 18]


In [7]:
arr2d = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

# Product of all elements
total_prod = np.prod(arr2d)
print("Total Product:", total_prod)


Total Product: 362880


In [8]:
arr2d = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

# Product along rows (axis=1)
row_prod = np.prod(arr2d, axis=1)
print("Product along rows (axis=1):", row_prod)


Product along rows (axis=1): [  6 120 504]


In [9]:
arr2d = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

# Product along columns (axis=0)
col_prod = np.prod(arr2d, axis=0)
print("Product along columns (axis=0):", col_prod)


Product along columns (axis=0): [ 28  80 162]


In [13]:
arr2d = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

# Cumulative sum along each row (axis=1)
cumsum_rows = np.cumsum(arr2d, axis=1)
print("Cumulative Sum along rows (axis=1):\n", cumsum_rows)


Cumulative Sum along rows (axis=1):
 [[ 1  3  6]
 [ 4  9 15]
 [ 7 15 24]]


In [15]:
arr2d = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

# Cumulative sum along each column (axis=0)
cumsum_cols = np.cumsum(arr2d, axis=0)
print("Cumulative Sum along columns (axis=0):\n", cumsum_cols)


Cumulative Sum along columns (axis=0):
 [[ 1  2  3]
 [ 5  7  9]
 [12 15 18]]


In [16]:
arr2d = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

# Cumulative product along each row (axis=1)
cumprod_rows = np.cumprod(arr2d, axis=1)
print("Cumulative Product along rows (axis=1):\n", cumprod_rows)


Cumulative Product along rows (axis=1):
 [[  1   2   6]
 [  4  20 120]
 [  7  56 504]]


In [17]:
arr2d = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

# Cumulative product along each column (axis=0)
cumprod_cols = np.cumprod(arr2d, axis=0)
print("Cumulative Product along columns (axis=0):\n", cumprod_cols)


Cumulative Product along columns (axis=0):
 [[  1   2   3]
 [  4  10  18]
 [ 28  80 162]]


In [20]:
arr2d = np.array([
    [1, 5, 9],
    [4, 9, 6],
    [2, 5, 9]
])


# Difference along rows (axis=1)
diff_rows = np.diff(arr2d, axis=1)
print("Difference along rows (axis=1):\n", diff_rows)

# Difference along columns (axis=0)
diff_cols = np.diff(arr2d, axis=0)
print("Difference along columns (axis=0):\n", diff_cols)


Difference along rows (axis=1):
 [[ 4  4]
 [ 5 -3]
 [ 3  4]]
Difference along columns (axis=0):
 [[ 3  4 -3]
 [-2 -4  3]]
